import type { TransitEngineStatus, TransitFoundationResult, TransitCalculationInput } from "@/lib/astrology/transit/types";

export function getTransitEngineStatus(): TransitEngineStatus {
  return {
    status: "blocked_until_provider_ready",
    verified: false,
    publicPredictionEnabled: false,
    reason: "Transit/gochar needs verified external planet position and ingress fixtures before public prediction can be activated.",
    requiredBeforeActivation: [
      "CI-safe ephemeris provider returning daily transit positions.",
      "Trusted ingress and retrograde fixtures for Sun, Moon, Mars, Mercury, Jupiter, Venus, Saturn, Rahu, and Ketu.",
      "Natal chart overlay rules for personalized transit results.",
      "Non-personalized educational content boundaries for any public transit page.",
      "Sitemap/robots review before route promotion."
    ]
  };
}

export function createBlockedTransitFoundationResult(input: TransitCalculationInput | null = null): TransitFoundationResult {
  return {
    input,
    positions: [],
    ingressWindows: [],
    metadata: {
      provider: "naksharix_transit_foundation",
      verificationLevel: "blocked_until_provider_ready",
      publicPredictionEnabled: false,
      limitations: [
        "No public transit prediction is enabled.",
        "No transit dates are generated by this foundation module.",
        "Exact transit validation requires trusted external ephemeris fixtures."
      ]
    }
  };
}
