import type { TransitEngineStatus, TransitFoundationResult, TransitCalculationInput } from "@/lib/astrology/transit/types";
import { calculateInternalChart } from "@/lib/astrology/premium-engine/chart";

export function getTransitEngineStatus(): TransitEngineStatus {
  return {
    status: "blocked_until_provider_ready",
    verified: false,
    publicPredictionEnabled: false,
    reason: "Transit/gochar needs verified external planet position and ingress fixtures before public prediction can be activated.",
    requiredBeforeActivation: [
      "CI-safe ephemeris provider returning daily transit positions.",
      "Trusted ingress and retrograde fixtures for Sun, Moon, Mars, Mercury, Jupiter, Venus, Saturn, Rahu, and Ketu.",
      "Natal chart overlay rules for personalized transit results.",
      "Non-personalized educational content boundaries for any public transit page.",
      "Sitemap/robots review before route promotion."
    ]
  };
}

export function createBlockedTransitFoundationResult(input: TransitCalculationInput | null = null): TransitFoundationResult {
  return {
    input,
    positions: [],
    ingressWindows: [],
    metadata: {
      provider: "naksharix_transit_foundation",
      verificationLevel: "blocked_until_provider_ready",
      publicPredictionEnabled: false,
      limitations: [
        "No public transit prediction is enabled.",
        "No transit dates are generated by this foundation module.",
        "Exact transit validation requires trusted external ephemeris fixtures."
      ]
    }
  };
}

export function calculateInternalTransitSnapshot(input: TransitCalculationInput): TransitFoundationResult {
  const chart = calculateInternalChart({
    date: input.date,
    time: "12:00",
    timezone: input.timezone,
    latitude: input.latitude ?? input.natalChart?.latitude ?? 0,
    longitude: input.longitude ?? input.natalChart?.longitude ?? 0,
    birthPlace: input.place ?? "Transit reference",
    ayanamsa: input.ayanamsa
  });

  return {
    input,
    positions: chart.planets.map((planet) => ({
      planet: planet.planet,
      sign: planet.sign,
      degree: planet.degree,
      absoluteLongitude: planet.absoluteLongitude ?? null,
      retrograde: planet.retrograde ?? null,
      verified: true
    })),
    ingressWindows: [],
    natalOverlay: {
      enabled: false,
      reason: "Natal overlay is not active until verified birth chart fixtures and transit rules are available."
    },
    metadata: {
      provider: "naksharix_astronomy_engine_lahiri_internal",
      verificationLevel: "provider_verified",
      publicPredictionEnabled: false,
      limitations: [
        "Transit positions are provider-regression-tested for fixed dates.",
        "Ingress windows and retrograde periods are not generated until external fixtures are verified.",
        "No public transit prediction should be activated from this internal snapshot alone."
      ]
    }
  };
}
