import type { normalizeKundliPdfData } from "@/lib/kundli/pdf-data";
import type { ComponentType, ReactElement } from "react";
import path from "node:path";

type PdfData = ReturnType<typeof normalizeKundliPdfData>;
type Locale = "en" | "hi" | "hinglish";
type PdfElementFactory = typeof import("react").createElement;
type PdfComponent = ComponentType<Record<string, unknown>>;
type PdfStyles = Record<string, unknown>;
type PdfTextFactory = (value: unknown, style?: unknown, props?: Record<string, unknown>) => ReactElement;

type PlanetRow = {
  planet?: unknown;
  sign?: unknown;
  house?: unknown;
  degree?: unknown;
  nakshatra?: unknown;
  pada?: unknown;
};

type DashaRow = {
  planet?: unknown;
  name?: unknown;
  startDate?: unknown;
  endDate?: unknown;
};

type ChartPlanet = {
  planet?: unknown;
  name?: unknown;
};

type ChartHouse = {
  house?: unknown;
  signNumber?: unknown;
  planets?: Array<string | ChartPlanet>;
};

type PdfFontRegistry = {
  register: (config: {
    family: string;
    fonts: Array<{ src: string; fontWeight?: string | number }>;
  }) => void;
};

const PDF_FONT_FAMILY = "NotoSansDevanagari";
let pdfFontsRegistered = false;

const labels = {
  en: {
    title: "Naksharix Kundli Report",
    birth: "Birth Details",
    panchang: "Panchang",
    avakahada: "Avakahada",
    planets: "Planetary Positions",
    charts: "Charts",
    dasha: "Vimshottari Dasha",
    summary: "Summary",
    remedies: "Remedies",
    disclaimer: "Disclaimer",
    name: "Name",
    gender: "Gender",
    dob: "Date of Birth",
    tob: "Time of Birth",
    place: "Birth Place",
    timezone: "Timezone",
    planet: "Planet",
    sign: "Sign",
    house: "House",
    degree: "Degree",
    nakshatra: "Nakshatra",
    pada: "Pada",
    start: "Start",
    end: "End",
    watermark: "Generated by Naksharix - Free Kundli Report",
    notAvailable: "Not available"
  },
  hi: {
    title: "Naksharix कुंडली रिपोर्ट",
    birth: "जन्म विवरण",
    panchang: "पंचांग",
    avakahada: "अवकहड़ा",
    planets: "ग्रह स्थिति तालिका",
    charts: "चार्ट",
    dasha: "विंशोत्तरी दशा",
    summary: "सारांश",
    remedies: "उपाय",
    disclaimer: "अस्वीकरण",
    name: "नाम",
    gender: "लिंग",
    dob: "जन्म तिथि",
    tob: "जन्म समय",
    place: "जन्म स्थान",
    timezone: "समय क्षेत्र",
    planet: "ग्रह",
    sign: "राशि",
    house: "भाव",
    degree: "डिग्री",
    nakshatra: "नक्षत्र",
    pada: "पद",
    start: "आरंभ",
    end: "समाप्ति",
    watermark: "Generated by Naksharix - Free Kundli Report",
    notAvailable: "उपलब्ध नहीं"
  },
  hinglish: {
    title: "Naksharix Kundli Report",
    birth: "Janm Details",
    panchang: "Panchang",
    avakahada: "Avakahada",
    planets: "Planetary Positions",
    charts: "Charts",
    dasha: "Vimshottari Dasha",
    summary: "Summary",
    remedies: "Upay",
    disclaimer: "Disclaimer",
    name: "Name",
    gender: "Gender",
    dob: "Date of Birth",
    tob: "Time of Birth",
    place: "Birth Place",
    timezone: "Timezone",
    planet: "Planet",
    sign: "Rashi",
    house: "Bhav",
    degree: "Degree",
    nakshatra: "Nakshatra",
    pada: "Pada",
    start: "Start",
    end: "End",
    watermark: "Generated by Naksharix - Free Kundli Report",
    notAvailable: "Available nahi hai"
  }
} as const;

export async function renderBundledKundliPdf(data: PdfData, language: Locale, pdfType: "FREE" | "PREMIUM") {
  const ReactForPdf = requirePdfReact();
  const { Document, Font, Line, Page, Rect, StyleSheet, Svg, Text, View, pdf } = await import("@react-pdf/renderer");
  registerPdfFonts(Font as PdfFontRegistry);
  const h = ReactForPdf.createElement;
  const PdfDocument = Document as unknown as PdfComponent;
  const PdfLine = Line as unknown as PdfComponent;
  const PdfPage = Page as unknown as PdfComponent;
  const PdfRect = Rect as unknown as PdfComponent;
  const PdfSvg = Svg as unknown as PdfComponent;
  const PdfText = Text as unknown as PdfComponent;
  const PdfView = View as unknown as PdfComponent;
  const lang = labels[language] ? language : "en";
  const styles = StyleSheet.create({
    page: { position: "relative", padding: 28, paddingBottom: 40, backgroundColor: "#fffaf0", color: "#241036", fontFamily: PDF_FONT_FAMILY, fontSize: 9.2, lineHeight: 1.35 },
    watermark: { position: "absolute", top: "43%", left: 24, right: 24, transform: "rotate(-28deg)", color: "#6d3bbd", opacity: 0.06, fontFamily: PDF_FONT_FAMILY, fontSize: 25, textAlign: "center", fontWeight: 800 },
    header: { marginBottom: 10, paddingBottom: 8, borderBottomWidth: 1.2, borderBottomColor: "#d4af37", display: "flex", flexDirection: "row", justifyContent: "space-between" },
    brand: { color: "#2b124d", fontSize: 21, fontWeight: 800, fontFamily: PDF_FONT_FAMILY },
    subtitle: { color: "#8b6a22", fontSize: 9 },
    section: { marginBottom: 8, padding: 8, borderWidth: 1, borderColor: "#dfc47a", borderRadius: 7, backgroundColor: "#fffdf8" },
    sectionTitle: { color: "#2b124d", fontSize: 11.5, fontWeight: 800, marginBottom: 6 },
    row: { display: "flex", flexDirection: "row", borderBottomWidth: 0.45, borderBottomColor: "#ead9aa", paddingVertical: 3.5 },
    key: { width: "38%", color: "#6d3bbd", fontWeight: 700 },
    value: { width: "62%", color: "#241036" },
    grid2: { display: "flex", flexDirection: "row", gap: 8 },
    col: { flex: 1 },
    chartRow: { display: "flex", flexDirection: "row", gap: 8 },
    chartBox: { flex: 1, padding: 6, borderWidth: 1, borderColor: "#d4af37", borderRadius: 6, backgroundColor: "#fff7df" },
    tableHeader: { display: "flex", flexDirection: "row", backgroundColor: "#2b124d", color: "#fff6d8", paddingVertical: 5, paddingHorizontal: 4, fontSize: 7.8, fontWeight: 800 },
    tableRow: { display: "flex", flexDirection: "row", paddingVertical: 4.3, paddingHorizontal: 4, borderBottomWidth: 0.45, borderBottomColor: "#e6d09a", fontSize: 7.8 },
    cellPlanet: { width: "15%" },
    cellSign: { width: "18%" },
    cellSmall: { width: "10%" },
    cellWide: { width: "24%" },
    paragraph: { marginBottom: 5, fontSize: 9.2, color: "#34223d" },
    footer: { position: "absolute", left: 28, right: 28, bottom: 16, display: "flex", flexDirection: "row", justifyContent: "space-between", color: "#7d6f83", fontSize: 7.5 }
  });

  const text: PdfTextFactory = (value, style, props = {}) => h(PdfText, { ...props, style }, safeText(value, lang));
  const row = (key: unknown, value: unknown) => h(PdfView, { key: `${safeText(key, lang)}-${safeText(value, lang)}`, style: styles.row }, [
    text(key, styles.key, { key: "k" }),
    text(value, styles.value, { key: "v" })
  ]);
  const section = (title: unknown, children: ReactElement[]) => h(PdfView, { key: safeText(title, lang), style: styles.section }, [
    text(title, styles.sectionTitle, { key: "title" }),
    ...children
  ]);

  const document = h(PdfDocument, { title: `${labels[lang].title} - ${safeText(data.personDetails?.name, lang)}`, author: "Naksharix" }, [
    page(h, text, PdfPage, PdfView, styles, lang, pdfType, labels[lang].title, [
      h(PdfView, { key: "top", style: styles.grid2 }, [
        h(PdfView, { key: "left", style: styles.col }, [
          section(labels[lang].birth, [
            row(labels[lang].name, data.personDetails?.name),
            row(labels[lang].gender, data.personDetails?.gender),
            row(labels[lang].dob, data.birthDetails?.dateOfBirth),
            row(labels[lang].tob, data.birthDetails?.timeOfBirth),
            row(labels[lang].place, data.birthDetails?.birthPlace),
            row(labels[lang].timezone, data.birthDetails?.timezone)
          ])
        ]),
        h(PdfView, { key: "right", style: styles.col }, [
          section(labels[lang].panchang, [
            row("Tithi / तिथि", data.panchang?.tithi),
            row("Paksha / पक्ष", data.panchang?.paksha),
            row("Vaar / वार", data.panchang?.vaar),
            row(labels[lang].nakshatra, data.panchang?.nakshatra),
            row("Yoga / योग", data.panchang?.yoga),
            row("Karan / करण", data.panchang?.karan)
          ])
        ])
      ]),
      h(PdfView, { key: "charts", style: styles.chartRow }, [
        chartPanel(h, text, PdfView, styles, PdfSvg, PdfRect, PdfLine, PdfText, labels[lang].charts + " D1", data.d1Chart, lang),
        chartPanel(h, text, PdfView, styles, PdfSvg, PdfRect, PdfLine, PdfText, "D9", data.d9Chart, lang),
        chartPanel(h, text, PdfView, styles, PdfSvg, PdfRect, PdfLine, PdfText, "Chalit", data.chalitChart, lang)
      ])
    ]),
    page(h, text, PdfPage, PdfView, styles, lang, pdfType, labels[lang].planets, [
      section(labels[lang].planets, [planetTable(h, text, PdfView, styles, data.planetaryPositions, lang)])
    ]),
    page(h, text, PdfPage, PdfView, styles, lang, pdfType, labels[lang].dasha, [
      section(labels[lang].dasha, [dashaTable(h, text, PdfView, styles, data.vimshottariDasha, lang)]),
      section(labels[lang].summary, [
        text(data.predictions?.lagnaAnalysis, styles.paragraph),
        text(data.predictions?.nakshatraAnalysis, styles.paragraph),
        text(data.predictions?.aiSummary, styles.paragraph)
      ])
    ]),
    page(h, text, PdfPage, PdfView, styles, lang, pdfType, labels[lang].remedies, [
      section(labels[lang].remedies, renderRemedies(text, data.remedies, lang, styles)),
      section(labels[lang].disclaimer, [text(data.predictions?.disclaimer, styles.paragraph)])
    ])
  ]);

  const stream = await pdf(document).toBuffer();
  const chunks: Buffer[] = [];
  for await (const chunk of stream as AsyncIterable<Buffer | Uint8Array | string>) {
    chunks.push(Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk));
  }
  const buffer = Buffer.concat(chunks);
  if (!buffer.length) throw new Error("Generated PDF buffer is empty");
  return buffer;
}

function page(
  h: PdfElementFactory,
  text: PdfTextFactory,
  Page: PdfComponent,
  View: PdfComponent,
  styles: PdfStyles,
  lang: Locale,
  pdfType: "FREE" | "PREMIUM",
  title: string,
  children: ReactElement[]
) {
  return h(Page, { key: title, size: "A4", style: styles.page }, [
    pdfType === "FREE" ? text(labels[lang].watermark, styles.watermark, { key: "watermark", fixed: true }) : null,
    h(View, { key: "header", fixed: true, style: styles.header }, [
      h(View, { key: "brand" }, [text("Naksharix", styles.brand, { key: "brand-text" }), text(title, styles.subtitle, { key: "sub" })]),
      text("naksharix.com", styles.subtitle, { key: "site" })
    ]),
    ...children,
    h(View, { key: "footer", fixed: true, style: styles.footer }, [text("naksharix.com", undefined, { key: "url" }), text(new Date().toISOString().slice(0, 10), undefined, { key: "date" })])
  ]);
}

function planetTable(h: PdfElementFactory, text: PdfTextFactory, View: PdfComponent, styles: PdfStyles, planets: unknown[], lang: Locale) {
  const rows: PlanetRow[] = Array.isArray(planets) && planets.length ? planets.map(toPlanetRow) : [{ planet: labels[lang].notAvailable }];
  return h(View, { key: "planet-table" }, [
    h(View, { key: "head", style: styles.tableHeader }, [
      text(labels[lang].planet, styles.cellPlanet, { key: "planet" }),
      text(labels[lang].sign, styles.cellSign, { key: "sign" }),
      text(labels[lang].house, styles.cellSmall, { key: "house" }),
      text(labels[lang].degree, styles.cellSmall, { key: "degree" }),
      text(labels[lang].nakshatra, styles.cellWide, { key: "nakshatra" }),
      text(labels[lang].pada, styles.cellSmall, { key: "pada" })
    ]),
    ...rows.map((planet, index) => h(View, { key: `planet-${index}`, style: styles.tableRow }, [
      text(planet?.planet, styles.cellPlanet, { key: "planet" }),
      text(planet?.sign, styles.cellSign, { key: "sign" }),
      text(planet?.house, styles.cellSmall, { key: "house" }),
      text(planet?.degree, styles.cellSmall, { key: "degree" }),
      text(planet?.nakshatra, styles.cellWide, { key: "nakshatra" }),
      text(planet?.pada, styles.cellSmall, { key: "pada" })
    ]))
  ]);
}

function dashaTable(h: PdfElementFactory, text: PdfTextFactory, View: PdfComponent, styles: PdfStyles, dashas: unknown[], lang: Locale) {
  const rows: DashaRow[] = Array.isArray(dashas) && dashas.length ? dashas.map(toDashaRow) : [{ planet: labels[lang].notAvailable }];
  return h(View, { key: "dasha-table" }, rows.map((dasha, index) => h(View, { key: `dasha-${index}`, style: styles.row }, [
    text(dasha?.planet ?? dasha?.name, styles.key, { key: "planet" }),
    text(`${safeText(dasha?.startDate, lang)} - ${safeText(dasha?.endDate, lang)}`, styles.value, { key: "dates" })
  ])));
}

function renderRemedies(text: PdfTextFactory, remedies: unknown[], lang: Locale, styles: PdfStyles) {
  if (!Array.isArray(remedies) || remedies.length === 0) return [text(labels[lang].notAvailable, styles.paragraph, { key: "empty" })];
  return remedies.map((remedy, index) => text(`• ${safeText(remedy, lang)}`, styles.paragraph, { key: `remedy-${index}` }));
}

function chartPanel(
  h: PdfElementFactory,
  text: PdfTextFactory,
  View: PdfComponent,
  styles: PdfStyles,
  Svg: PdfComponent,
  Rect: PdfComponent,
  Line: PdfComponent,
  SvgText: PdfComponent,
  title: string,
  houses: unknown[],
  lang: Locale
) {
  return h(View, { key: title, style: styles.chartBox, wrap: false }, [
    text(title, styles.sectionTitle, { key: "title" }),
    Array.isArray(houses) && houses.length ? chart(h, View, Svg, Rect, Line, SvgText, houses, lang) : text(labels[lang].notAvailable, styles.paragraph, { key: "empty" })
  ]);
}

function chart(
  h: PdfElementFactory,
  View: PdfComponent,
  Svg: PdfComponent,
  Rect: PdfComponent,
  Line: PdfComponent,
  SvgText: PdfComponent,
  houses: unknown[],
  lang: Locale
) {
  const chartLayout: Record<number, { signX: number; signY: number; planetX: number; planetY: number }> = {
    1: { signX: 150, signY: 32, planetX: 150, planetY: 54 }, 2: { signX: 78, signY: 24, planetX: 88, planetY: 56 },
    3: { signX: 34, signY: 78, planetX: 56, planetY: 100 }, 4: { signX: 78, signY: 136, planetX: 88, planetY: 156 },
    5: { signX: 34, signY: 186, planetX: 56, planetY: 204 }, 6: { signX: 86, signY: 236, planetX: 96, planetY: 254 },
    7: { signX: 150, signY: 220, planetX: 150, planetY: 244 }, 8: { signX: 214, signY: 236, planetX: 204, planetY: 254 },
    9: { signX: 266, signY: 186, planetX: 244, planetY: 204 }, 10: { signX: 222, signY: 136, planetX: 212, planetY: 156 },
    11: { signX: 266, signY: 78, planetX: 244, planetY: 100 }, 12: { signX: 214, signY: 24, planetX: 204, planetY: 56 }
  };
  const lines = [[0, 0, 300, 280], [300, 0, 0, 280], [150, 0, 300, 140], [300, 140, 150, 280], [150, 280, 0, 140], [0, 140, 150, 0], [75, 70, 225, 70], [75, 210, 225, 210], [75, 70, 75, 210], [225, 70, 225, 210]];
  return h(View, { key: "chart-view", wrap: false, style: { width: 150, marginVertical: 4 } }, [
    h(Svg, { key: "svg", width: 150, height: 140, viewBox: "0 0 300 280" }, [
      h(Rect, { key: "border", x: 1, y: 1, width: 298, height: 278, fill: "#fff7df", stroke: "#2e1b0d", strokeWidth: 2 }),
      ...lines.map(([x1, y1, x2, y2], index) => h(Line, { key: `line-${index}`, x1, y1, x2, y2, stroke: "#2e1b0d", strokeWidth: index < 6 ? 1.4 : 1.1 })),
      ...Array.from({ length: 12 }, (_, index) => {
        const houseNumber = index + 1;
        const house = houses.map(toChartHouse).find((item) => Number(item.house) === houseNumber) ?? { house: houseNumber, planets: [] };
        const layout = chartLayout[houseNumber];
        const planets = planetLabels(house, lang).slice(0, 4);
        return [
          h(SvgText, { key: "sign", x: layout.signX, y: layout.signY, textAnchor: "middle", fill: "#7b4b16", style: { fontFamily: PDF_FONT_FAMILY, fontSize: 12, fontWeight: "bold" } }, safeText(house?.signNumber ?? "-", lang)),
          ...(planets.length ? planets : ["-"]).map((planet, planetIndex) => h(SvgText, { key: `p-${planetIndex}`, x: layout.planetX, y: layout.planetY + planetIndex * 15, textAnchor: "middle", fill: "#3a2110", style: { fontFamily: PDF_FONT_FAMILY, fontSize: 10.5, fontWeight: "bold" } }, safeText(planet, lang)))
        ];
      }).flat()
    ])
  ]);
}

function registerPdfFonts(Font: PdfFontRegistry) {
  if (pdfFontsRegistered) return;
  const fontDir = path.join(process.cwd(), "public", "fonts");
  Font.register({
    family: PDF_FONT_FAMILY,
    fonts: [
      { src: path.join(fontDir, "NotoSansDevanagari-Regular.ttf"), fontWeight: 400 },
      { src: path.join(fontDir, "NotoSansDevanagari-Bold.ttf"), fontWeight: 700 },
      { src: path.join(fontDir, "NotoSansDevanagari-Bold.ttf"), fontWeight: 800 }
    ]
  });
  pdfFontsRegistered = true;
}

function planetLabels(house: ChartHouse, lang: Locale) {
  const planets = Array.isArray(house?.planets) ? house.planets : [];
  return planets.map((planet) => shortPlanet(typeof planet === "string" ? planet : planet.planet ?? planet.name, lang)).filter(Boolean);
}

function toPlanetRow(value: unknown): PlanetRow {
  return isRecord(value) ? value : { planet: safeText(value, "en") };
}

function toDashaRow(value: unknown): DashaRow {
  return isRecord(value) ? value : { planet: safeText(value, "en") };
}

function toChartHouse(value: unknown): ChartHouse {
  if (!isRecord(value)) return { planets: [] };
  const planets = Array.isArray(value.planets) ? value.planets.map(toChartPlanet) : [];
  return { house: value.house, signNumber: value.signNumber, planets };
}

function toChartPlanet(value: unknown): string | ChartPlanet {
  if (typeof value === "string") return value;
  if (!isRecord(value)) return safeText(value, "en");
  return { planet: value.planet, name: value.name };
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function shortPlanet(planet: unknown, lang: Locale) {
  const raw = safeText(planet, lang);
  const map: Record<string, string> = { Sun: "Su", Moon: "Mo", Mars: "Ma", Mercury: "Me", Jupiter: "Ju", Venus: "Ve", Saturn: "Sa", Rahu: "Ra", Ketu: "Ke", Ascendant: "As", Lagna: "As" };
  return map[raw] ?? raw.slice(0, 3);
}

function safeText(value: unknown, lang: Locale): string {
  if (value === null || value === undefined || value === "") return labels[lang].notAvailable;
  if (typeof value === "string" || typeof value === "number" || typeof value === "boolean") return String(value);
  if (Array.isArray(value)) return value.map((item) => safeText(item, lang)).join(", ");
  if (typeof value === "object") {
    const obj = value as Record<string, unknown>;
    if ("name" in obj) return safeText(obj.name, lang);
    if ("label" in obj) return safeText(obj.label, lang);
    if ("value" in obj) return safeText(obj.value, lang);
    if ("sign" in obj) return safeText(obj.sign, lang);
    if ("house" in obj) return safeText(obj.house, lang);
    if ("planet" in obj) return safeText(obj.planet, lang);
    return JSON.stringify(obj);
  }
  return String(value);
}

function requirePdfReact() {
  const getBuiltinModule = (process as typeof process & {
    getBuiltinModule?: (name: string) => typeof import("node:module");
  }).getBuiltinModule;
  const nodeModule = getBuiltinModule?.("module");
  const externalRequire = nodeModule?.createRequire(`${process.cwd()}/package.json`);
  if (!externalRequire) throw new Error("Node module loader unavailable for PDF renderer");
  return externalRequire("react") as typeof import("react");
}
