import type { normalizeKundliPdfData } from "@/lib/kundli/pdf-data";
import { translateAstroValue, translatePlanet, translateSign, type AstroValueCategory } from "@/lib/kundli/chart-mapping";
import type { ComponentType, ReactElement } from "react";
import fs from "node:fs";
import path from "node:path";

type PdfData = ReturnType<typeof normalizeKundliPdfData>;
type Locale = "en" | "hi" | "hinglish";
type PdfElementFactory = typeof import("react").createElement;
type PdfComponent = ComponentType<Record<string, unknown>>;
type PdfStyles = Record<string, unknown>;
type PdfTextFactory = (value: unknown, style?: unknown, props?: Record<string, unknown>) => ReactElement;

type PlanetRow = {
  planet?: unknown;
  sign?: unknown;
  house?: unknown;
  degree?: unknown;
  nakshatra?: unknown;
  pada?: unknown;
};

type DashaRow = {
  planet?: unknown;
  name?: unknown;
  startDate?: unknown;
  endDate?: unknown;
  startsAt?: unknown;
  endsAt?: unknown;
};

type ChartPlanet = {
  planet?: unknown;
  name?: unknown;
};

type ChartHouse = {
  house?: unknown;
  sign?: unknown;
  signNumber?: unknown;
  planets?: Array<string | ChartPlanet>;
};

type PdfFontRegistry = {
  register: (config: {
    family: string;
    fonts: Array<{ src: string; fontWeight?: string | number }>;
  }) => void;
  registerHyphenationCallback?: (callback: (word: string) => string[]) => void;
};

const PDF_FONT_FAMILY = "NotoSansDevanagari";
const PDF_LOGO_PATH = path.join(process.cwd(), "public", "images", "naksharix-final-logo-symbol.png");
const PDF_LOGO_MIME = "image/png";
let pdfFontsRegistered = false;
let pdfLogoDataUri: string | null | undefined;

const labels = {
  en: {
    title: "Naksharix Kundli Report",
    birth: "Birth Details",
    panchang: "Panchang",
    avakahada: "Avakahada",
    planets: "Planetary Positions",
    charts: "Charts",
    dasha: "Vimshottari Dasha",
    currentMahadasha: "Current Mahadasha",
    currentAntardasha: "Current Antardasha",
    dashaBalance: "Dasha Balance",
    dashaTimeline: "Dasha Timeline",
    summary: "Summary",
    remedies: "Remedies",
    disclaimer: "Disclaimer",
    name: "Name",
    gender: "Gender",
    dob: "Date of Birth",
    tob: "Time of Birth",
    place: "Birth Place",
    timezone: "Timezone",
    lagna: "Lagna",
    finance: "Finance",
    planet: "Planet",
    sign: "Sign",
    house: "House",
    degree: "Degree",
    nakshatra: "Nakshatra",
    pada: "Pada",
    start: "Start",
    end: "End",
    tithi: "Tithi",
    paksha: "Paksha",
    vaar: "Vaar / Day",
    yoga: "Yoga",
    karan: "Karan",
    d1Chart: "D1 Lagna Chart",
    d9Chart: "D9 Navamsa Chart",
    chalitChart: "Chalit Chart",
    chalitMethod: "Chalit Method",
    d1House: "D1 House",
    chalitHouse: "Chalit House",
    movement: "Movement",
    doshaAnalysis: "Dosha Analysis",
    manglikStatus: "Manglik Status",
    kaalSarpStatus: "Kaal Sarp Signal",
    yogaAnalysis: "Yoga Analysis",
    detectedYogas: "Detected Yogas",
    noYoga: "No major yoga was detected from the currently available data.",
    lagnaSummary: "Lagna Summary",
    nakshatraSummary: "Nakshatra Summary",
    careerOverview: "Career Overview",
    relationshipOverview: "Relationship Overview",
    healthOverview: "Health / Well-being Overview",
    generalRemedies: "General Remedies",
    dashaUnavailable: "Dasha details are currently unavailable. Review the chart and planetary insights below.",
    interpretationUnavailable: "AI interpretation is currently limited. Use the available chart, Panchang, and planetary sections for grounded reflection.",
    nativeName: "Native",
    reportLanguage: "Report Language",
    generatedDate: "Generated Date",
    intro: "This free Naksharix report is built from the available birth details, Panchang, charts, and planetary positions. It is designed for reflection, planning, and spiritual-tech guidance.",
    personalityStyle: "Personality Style",
    strengths: "Strengths",
    growthAreas: "Growth Areas",
    moonSign: "Moon Sign",
    emotionalNature: "Emotional Nature",
    mindsetInstincts: "Mindset and Instincts",
    practicalGuidance: "Practical Guidance",
    planetWiseInterpretation: "Planet-wise Interpretation",
    positivePotential: "Positive Potential",
    cautionGrowth: "Caution / Growth Area",
    houseWiseLifeAreas: "House-wise Life Areas",
    detailedAnalysis: "Detailed Kundli Analysis",
    careerFinance: "Career and Finance Analysis",
    relationshipMarriage: "Relationship and Marriage Analysis",
    healthWellbeing: "Health and Well-being Analysis",
    timingGuidance: "Timing Guidance",
    finalSummary: "Final Summary",
    nextSteps: "Next Steps",
    premiumCta: "Premium reports add deeper timing, yogas, dosha notes, personalized remedies, and expanded interpretation where exact data is available.",
    freeReport: "FREE KUNDLI REPORT",
    premiumReport: "PREMIUM KUNDLI REPORT",
    brandSubtitle: "COSMIC DESTINY",
    generatedBy: "Generated by Naksharix",
    pageLabel: "Page",
    cleanUnavailable: "Not available",
    dash: "-",
    watermark: "Generated by Naksharix - Free Kundli Report",
    notAvailable: "Not available"
  },
  hi: {
    title: "नक्षत्रिक्स कुंडली रिपोर्ट",
    birth: "जन्म विवरण",
    panchang: "पंचांग",
    avakahada: "अवकहड़ा",
    planets: "ग्रह स्थिति तालिका",
    charts: "चार्ट",
    dasha: "विंशोत्तरी दशा",
    currentMahadasha: "वर्तमान महादशा",
    currentAntardasha: "वर्तमान अंतर्दशा",
    dashaBalance: "दशा शेष",
    dashaTimeline: "दशा समयरेखा",
    summary: "सारांश",
    remedies: "उपाय",
    disclaimer: "अस्वीकरण",
    name: "नाम",
    gender: "लिंग",
    dob: "जन्म तिथि",
    tob: "जन्म समय",
    place: "जन्म स्थान",
    timezone: "समय क्षेत्र",
    lagna: "लग्न",
    finance: "वित्त",
    planet: "ग्रह",
    sign: "राशि",
    house: "भाव",
    degree: "डिग्री",
    nakshatra: "नक्षत्र",
    pada: "पद",
    start: "आरंभ",
    end: "समाप्ति",
    tithi: "तिथि",
    paksha: "पक्ष",
    vaar: "वार / दिन",
    yoga: "योग",
    karan: "करण",
    d1Chart: "D1 लग्न चार्ट",
    d9Chart: "D9 नवांश चार्ट",
    chalitChart: "चलित चार्ट",
    chalitMethod: "चलित विधि",
    d1House: "D1 भाव",
    chalitHouse: "चलित भाव",
    movement: "भाव परिवर्तन",
    doshaAnalysis: "दोष विश्लेषण",
    manglikStatus: "मांगलिक स्थिति",
    kaalSarpStatus: "काल सर्प संकेत",
    yogaAnalysis: "योग विश्लेषण",
    detectedYogas: "मिले हुए योग",
    noYoga: "उपलब्ध डेटा से कोई प्रमुख योग स्पष्ट रूप से नहीं मिला।",
    lagnaSummary: "लग्न सारांश",
    nakshatraSummary: "नक्षत्र सारांश",
    careerOverview: "करियर अवलोकन",
    relationshipOverview: "संबंध अवलोकन",
    healthOverview: "स्वास्थ्य / कल्याण अवलोकन",
    generalRemedies: "सामान्य उपाय",
    dashaUnavailable: "दशा विवरण अभी उपलब्ध नहीं है। ग्रह स्थिति और जन्म चार्ट के आधार पर आगे का विश्लेषण देखें।",
    interpretationUnavailable: "AI व्याख्या अभी सीमित है। उपलब्ध चार्ट, पंचांग और ग्रह स्थिति के आधार पर शांत चिंतन करें।",
    nativeName: "जातक",
    reportLanguage: "रिपोर्ट भाषा",
    generatedDate: "निर्मित तिथि",
    intro: "यह मुफ्त नक्षत्रिक्स रिपोर्ट उपलब्ध जन्म विवरण, पंचांग, चार्ट और ग्रह स्थिति के आधार पर बनाई गई है। इसका उद्देश्य आत्मचिंतन, योजना और आध्यात्मिक-तकनीकी मार्गदर्शन है।",
    personalityStyle: "व्यक्तित्व शैली",
    strengths: "शक्तियां",
    growthAreas: "विकास क्षेत्र",
    moonSign: "चंद्र राशि",
    emotionalNature: "भावनात्मक स्वभाव",
    mindsetInstincts: "मानसिकता और सहज प्रवृत्ति",
    practicalGuidance: "व्यावहारिक मार्गदर्शन",
    planetWiseInterpretation: "ग्रहवार व्याख्या",
    positivePotential: "सकारात्मक क्षमता",
    cautionGrowth: "सावधानी / विकास क्षेत्र",
    houseWiseLifeAreas: "भाववार जीवन क्षेत्र",
    detailedAnalysis: "विस्तृत कुंडली विश्लेषण",
    careerFinance: "करियर और वित्त विश्लेषण",
    relationshipMarriage: "संबंध और विवाह विश्लेषण",
    healthWellbeing: "स्वास्थ्य और कल्याण विश्लेषण",
    timingGuidance: "समय मार्गदर्शन",
    finalSummary: "अंतिम सारांश",
    nextSteps: "अगले कदम",
    premiumCta: "प्रीमियम रिपोर्ट में उपलब्ध सटीक डेटा के आधार पर गहरा समय विश्लेषण, योग, दोष नोट्स, व्यक्तिगत उपाय और विस्तृत व्याख्या जोड़ी जाती है।",
    freeReport: "मुफ्त कुंडली रिपोर्ट",
    premiumReport: "प्रीमियम कुंडली रिपोर्ट",
    brandSubtitle: "COSMIC DESTINY",
    generatedBy: "नक्षत्रिक्स द्वारा निर्मित",
    pageLabel: "पृष्ठ",
    cleanUnavailable: "उपलब्ध नहीं",
    dash: "—",
    watermark: "नक्षत्रिक्स द्वारा निर्मित - मुफ्त कुंडली रिपोर्ट",
    notAvailable: "उपलब्ध नहीं"
  },
  hinglish: {
    title: "Naksharix Kundli Report",
    birth: "Janm Details",
    panchang: "Panchang",
    avakahada: "Avakahada",
    planets: "Planetary Positions",
    charts: "Charts",
    dasha: "Vimshottari Dasha",
    currentMahadasha: "Current Mahadasha",
    currentAntardasha: "Current Antardasha",
    dashaBalance: "Dasha Balance",
    dashaTimeline: "Dasha Timeline",
    summary: "Summary",
    remedies: "Upay",
    disclaimer: "Disclaimer",
    name: "Name",
    gender: "Gender",
    dob: "Date of Birth",
    tob: "Time of Birth",
    place: "Birth Place",
    timezone: "Timezone",
    lagna: "Lagna",
    finance: "Finance",
    planet: "Planet",
    sign: "Rashi",
    house: "Bhav",
    degree: "Degree",
    nakshatra: "Nakshatra",
    pada: "Pada",
    start: "Start",
    end: "End",
    tithi: "Tithi",
    paksha: "Paksha",
    vaar: "Vaar / Day",
    yoga: "Yoga",
    karan: "Karan",
    d1Chart: "D1 Lagna Chart",
    d9Chart: "D9 Navamsa Chart",
    chalitChart: "Chalit Chart",
    chalitMethod: "Chalit Method",
    d1House: "D1 House",
    chalitHouse: "Chalit House",
    movement: "Movement",
    doshaAnalysis: "Dosha Analysis",
    manglikStatus: "Manglik Status",
    kaalSarpStatus: "Kaal Sarp Signal",
    yogaAnalysis: "Yoga Analysis",
    detectedYogas: "Detected Yogas",
    noYoga: "Available data se koi major yoga clearly detect nahi hua.",
    lagnaSummary: "Lagna Summary",
    nakshatraSummary: "Nakshatra Summary",
    careerOverview: "Career Overview",
    relationshipOverview: "Relationship Overview",
    healthOverview: "Health / Well-being Overview",
    generalRemedies: "General Upay",
    dashaUnavailable: "Dasha details abhi available nahi hain. Chart aur planetary insights below review karein.",
    interpretationUnavailable: "AI interpretation abhi limited hai. Available chart, Panchang aur grah sections se grounded reflection karein.",
    nativeName: "Jatak",
    reportLanguage: "Report Language",
    generatedDate: "Generated Date",
    intro: "Yeh free Naksharix report available birth details, Panchang, charts aur grah positions se bani hai. Iska purpose reflection, planning aur spiritual-tech guidance hai.",
    personalityStyle: "Personality Style",
    strengths: "Strengths",
    growthAreas: "Growth Areas",
    moonSign: "Moon Sign",
    emotionalNature: "Emotional Nature",
    mindsetInstincts: "Mindset aur Instincts",
    practicalGuidance: "Practical Guidance",
    planetWiseInterpretation: "Planet-wise Interpretation",
    positivePotential: "Positive Potential",
    cautionGrowth: "Caution / Growth Area",
    houseWiseLifeAreas: "House-wise Life Areas",
    detailedAnalysis: "Detailed Kundli Analysis",
    careerFinance: "Career aur Finance Analysis",
    relationshipMarriage: "Relationship aur Marriage Analysis",
    healthWellbeing: "Health aur Well-being Analysis",
    timingGuidance: "Timing Guidance",
    finalSummary: "Final Summary",
    nextSteps: "Next Steps",
    premiumCta: "Premium reports me exact data available hone par deeper timing, yogas, dosha notes, personalized remedies aur expanded interpretation add hota hai.",
    freeReport: "Free Kundli Report",
    premiumReport: "Premium Kundli Report",
    brandSubtitle: "COSMIC DESTINY",
    generatedBy: "Naksharix dwara generated",
    pageLabel: "Page",
    cleanUnavailable: "Available nahi hai",
    dash: "-",
    watermark: "Generated by Naksharix - Free Kundli Report",
    notAvailable: "Available nahi hai"
  }
} as const;

export async function renderBundledKundliPdf(data: PdfData, language: Locale, pdfType: "FREE" | "PREMIUM") {
  const ReactForPdf = requirePdfReact();
  const { Document, Font, Image, Line, Page, Rect, StyleSheet, Svg, Text, View, pdf } = await import("@react-pdf/renderer");
  registerPdfFonts(Font as PdfFontRegistry);
  const h = ReactForPdf.createElement;
  const PdfDocument = Document as unknown as PdfComponent;
  const PdfImage = Image as unknown as PdfComponent;
  const PdfLine = Line as unknown as PdfComponent;
  const PdfPage = Page as unknown as PdfComponent;
  const PdfRect = Rect as unknown as PdfComponent;
  const PdfSvg = Svg as unknown as PdfComponent;
  const PdfText = Text as unknown as PdfComponent;
  const PdfView = View as unknown as PdfComponent;
  const lang = labels[language] ? language : "en";
  const isHindi = lang === "hi";
  const logoSource = loadPdfLogoSource();
  const styles = StyleSheet.create({
    page: { position: "relative", padding: isHindi ? 24 : 28, paddingTop: isHindi ? 22 : 24, paddingBottom: 40, backgroundColor: "#020612", color: "#ffffff", fontFamily: PDF_FONT_FAMILY, fontSize: isHindi ? 8.55 : 9, lineHeight: isHindi ? 1.34 : 1.36 },
    watermark: { position: "absolute", top: "40%", left: 55, right: 55, transform: "rotate(-26deg)", opacity: 0.06, display: "flex", alignItems: "center" },
    watermarkLogo: { width: 96, height: 96, objectFit: "contain", marginBottom: 6 },
    watermarkText: { color: "#f3d382", fontSize: isHindi ? 25 : 28, textAlign: "center", fontWeight: 800, letterSpacing: isHindi ? 0 : 1.5 },
    watermarkSubtext: { color: "#ffffff", fontSize: 8, textAlign: "center", marginTop: 1, letterSpacing: isHindi ? 0 : 2.4 },
    header: { marginBottom: isHindi ? 5 : 7, paddingBottom: isHindi ? 5 : 7, borderBottomWidth: 1.2, borderBottomColor: "#dca956", display: "flex", flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
    brandBlock: { width: "56%", display: "flex", flexDirection: "row", alignItems: "center" },
    logo: { width: 28, height: 28, objectFit: "contain", marginRight: 8 },
    brandTextBlock: { display: "flex", flexDirection: "column" },
    brand: { color: "#f3d382", fontSize: 14, fontWeight: 800, fontFamily: PDF_FONT_FAMILY, lineHeight: 1.05, letterSpacing: isHindi ? 0 : 0.8 },
    brandSubtitle: { color: "#94a3b8", fontSize: 6.8, letterSpacing: isHindi ? 0 : 1.6, marginTop: 1 },
    headerMeta: { width: "42%" },
    headerTitle: { color: "#f3d382", fontSize: isHindi ? 9.4 : 8.8, fontWeight: 700, textAlign: "right", marginBottom: 2, lineHeight: isHindi ? 1.34 : 1.15 },
    site: { color: "#94a3b8", fontSize: 7.4, textAlign: "right" },
    reportTitle: { color: "#f3d382", fontSize: isHindi ? 11.4 : 12.2, fontWeight: 800, marginBottom: isHindi ? 6 : 8, lineHeight: isHindi ? 1.26 : 1.2 },
    subtitle: { color: "#94a3b8", fontSize: 9, lineHeight: isHindi ? 1.45 : 1.25 },
    content: { marginTop: 2 },
    section: { marginBottom: isHindi ? 5.5 : 7, padding: isHindi ? 6.5 : 8, borderWidth: 1, borderColor: "#1e293b", borderRadius: 7, backgroundColor: "#0a1224" },
    sectionTitle: { color: "#f3d382", fontSize: isHindi ? 10.3 : 10.8, fontWeight: 800, marginBottom: isHindi ? 4.5 : 6, lineHeight: isHindi ? 1.24 : 1.18 },
    row: { display: "flex", flexDirection: "row", borderBottomWidth: 0.45, borderBottomColor: "#1e293b", paddingVertical: isHindi ? 2.8 : 3.5 },
    key: { width: "38%", color: "#dca956", fontWeight: 700, paddingRight: 5, lineHeight: isHindi ? 1.3 : 1.25 },
    value: { width: "62%", color: "#ffffff", lineHeight: isHindi ? 1.3 : 1.25 },
    grid2: { display: "flex", flexDirection: "row", gap: 8 },
    col: { flex: 1 },
    chartRow: { display: "flex", flexDirection: "column", gap: 7, marginTop: 2, marginBottom: 8 },
    chartBox: { padding: isHindi ? 7 : 8, borderWidth: 1.2, borderColor: "#334155", borderRadius: 7, backgroundColor: "#0f1c3a" },
    chartTitle: { color: "#f3d382", fontSize: isHindi ? 10.5 : 10.7, fontWeight: 800, marginBottom: 5, lineHeight: isHindi ? 1.28 : 1.16 },
    chartGrid: { display: "flex", flexDirection: "row", flexWrap: "wrap", gap: 4 },
    chartHouseCard: { width: "23.5%", minHeight: isHindi ? 45 : 43, padding: 4.5, borderWidth: 0.8, borderColor: "#1e293b", borderRadius: 5, backgroundColor: "#0a1224" },
    chartHouseHeader: { color: "#fbc02d", fontSize: isHindi ? 7.2 : 7.4, fontWeight: 800, marginBottom: 1.8, lineHeight: isHindi ? 1.2 : 1.1 },
    chartHouseSign: { color: "#f3d382", fontSize: isHindi ? 8.1 : 8.3, fontWeight: 700, marginBottom: 2.5, lineHeight: isHindi ? 1.24 : 1.15 },
    chartPlanetLine: { color: "#ffffff", fontSize: isHindi ? 8.7 : 8.3, fontWeight: 800, lineHeight: isHindi ? 1.34 : 1.22 },
    chartNote: { marginBottom: 7, padding: 8, borderWidth: 1, borderColor: "#1e293b", borderRadius: 7, backgroundColor: "#0a1224" },
    tableHeader: { display: "flex", flexDirection: "row", backgroundColor: "#0f1c3a", color: "#f3d382", paddingVertical: 4.8, paddingHorizontal: 4, fontSize: isHindi ? 7.8 : 7.5, fontWeight: 800, lineHeight: 1.24 },
    tableRow: { display: "flex", flexDirection: "row", paddingVertical: isHindi ? 4.2 : 3.8, paddingHorizontal: 4, borderBottomWidth: 0.45, borderBottomColor: "#1e293b", fontSize: isHindi ? 7.8 : 7.5, lineHeight: isHindi ? 1.36 : 1.22, color: "#ffffff" },
    cellPlanet: { width: "15%" },
    cellSign: { width: "18%" },
    cellSmall: { width: "10%" },
    cellWide: { width: "24%" },
    paragraph: { marginBottom: isHindi ? 4.1 : 5.2, fontSize: isHindi ? 8.7 : 9, color: "#ffffff", lineHeight: isHindi ? 1.35 : 1.36 },
    mutedParagraph: { marginBottom: isHindi ? 4.1 : 5.2, fontSize: isHindi ? 8.25 : 8.6, color: "#94a3b8", lineHeight: isHindi ? 1.32 : 1.32 },
    goldParagraph: { marginBottom: isHindi ? 4.1 : 5.2, fontSize: isHindi ? 8.7 : 9, color: "#f3d382", lineHeight: isHindi ? 1.35 : 1.36, fontWeight: 700 },
    coverPanel: { marginBottom: isHindi ? 6 : 8, padding: isHindi ? 11 : 14, borderWidth: 1.3, borderColor: "#dca956", borderRadius: 10, backgroundColor: "#0a1224" },
    coverBrandRow: { display: "flex", flexDirection: "row", alignItems: "center", marginBottom: isHindi ? 8 : 11 },
    coverLogo: { width: isHindi ? 58 : 72, height: isHindi ? 58 : 72, objectFit: "contain", marginRight: 12 },
    coverBrandName: { color: "#f3d382", fontSize: isHindi ? 21 : 24, fontWeight: 800, letterSpacing: isHindi ? 0 : 1.5, lineHeight: 1.02 },
    coverBrandSubtitle: { color: "#94a3b8", fontSize: 8.5, letterSpacing: isHindi ? 0 : 2.6, marginTop: 3 },
    coverDivider: { height: 1.2, backgroundColor: "#dca956", marginBottom: isHindi ? 7 : 10, opacity: 0.9 },
    coverTitle: { color: "#f3d382", fontSize: isHindi ? 15.5 : 18.5, fontWeight: 800, marginBottom: isHindi ? 4 : 6, lineHeight: isHindi ? 1.18 : 1.08 },
    coverSubtitle: { color: "#94a3b8", fontSize: isHindi ? 8.2 : 9, lineHeight: isHindi ? 1.27 : 1.28 },
    badge: { alignSelf: "flex-start", marginBottom: 8, paddingVertical: 4, paddingHorizontal: 8, borderWidth: 1, borderColor: "#1e293b", borderRadius: 999, color: "#00f5a0", backgroundColor: "#0f1c3a", fontSize: 8.2, fontWeight: 700 },
    bullet: { marginBottom: 4, color: "#ffffff", fontSize: isHindi ? 9.4 : 8.9, lineHeight: isHindi ? 1.52 : 1.35 },
    footer: { position: "absolute", left: 30, right: 30, bottom: 15, paddingTop: 5, borderTopWidth: 0.6, borderTopColor: "#1e293b", display: "flex", flexDirection: "row", justifyContent: "space-between", color: "#94a3b8", fontSize: 7.2 },
    footerText: { color: "#94a3b8", fontSize: 7.2 },
    pageCounter: { color: "#f3d382", fontSize: 7.2, fontWeight: 700 }
  });

  const text: PdfTextFactory = (value, style, props = {}) => h(PdfText, { ...props, style: pdfTextStyle(style, lang) }, safeText(value, lang));
  const row = (key: unknown, value: unknown) => h(PdfView, { key: `${safeText(key, lang)}-${safeText(value, lang)}`, style: styles.row }, [
    text(key, styles.key, { key: "k" }),
    text(value, styles.value, { key: "v" })
  ]);
  const section = (title: unknown, children: ReactElement[]) => h(PdfView, { key: safeText(title, lang), style: styles.section }, [
    text(title, styles.sectionTitle, { key: "title" }),
    ...children
  ]);
  const fixedSection = (title: unknown, children: ReactElement[]) => h(PdfView, { key: safeText(title, lang), style: styles.section, wrap: false }, [
    text(title, styles.sectionTitle, { key: "title" }),
    ...children
  ]);
  const paragraph = (value: unknown, key: string, style = styles.paragraph) => text(value, style, { key });
  const bullets = (items: unknown[], keyPrefix: string) => items.map((item, index) => text(`• ${safeText(item, lang)}`, styles.bullet, { key: `${keyPrefix}-${index}` }));
  const generatedDate = new Date().toISOString().slice(0, 10);
  const makePage = (title: string, children: ReactElement[]) => page(h, text, PdfPage, PdfView, PdfImage, PdfText, styles, lang, title, generatedDate, logoSource, children);

  const ascendant = translateSignValue(data.avakahada?.ascendant, lang);
  const moonSign = translateSignValue(data.avakahada?.moonSign, lang);
  const birthRows = [
    row(labels[lang].name, data.personDetails?.name),
    row(labels[lang].gender, translateGender(data.personDetails?.gender, lang)),
    row(labels[lang].dob, data.birthDetails?.dateOfBirth),
    row(labels[lang].tob, data.birthDetails?.timeOfBirth),
    row(labels[lang].place, data.birthDetails?.birthPlace),
    row(labels[lang].timezone, data.birthDetails?.timezone)
  ];
  const panchangRows = [
    row(labels[lang].tithi, translateByCategory(data.panchang?.tithi, lang, "tithi")),
    row(labels[lang].paksha, translateByCategory(data.panchang?.paksha, lang, "paksha")),
    row(labels[lang].vaar, translateByCategory(data.panchang?.vaar, lang, "weekday")),
    row(labels[lang].nakshatra, translateByCategory(data.panchang?.nakshatra, lang, "nakshatra")),
    row(labels[lang].yoga, translateByCategory(data.panchang?.yoga, lang, "yoga")),
    row(labels[lang].karan, translateByCategory(data.panchang?.karan, lang, "karan"))
  ];

  const document = h(PdfDocument, { title: `${labels[lang].title} - ${safeText(data.personDetails?.name, lang)}`, author: "Naksharix" }, [
    makePage(labels[lang].title, [
      h(PdfView, { key: "cover", style: styles.coverPanel }, [
        h(PdfView, { key: "cover-brand", style: styles.coverBrandRow }, [
          logoSource ? h(PdfImage, { key: "cover-logo", src: logoSource, style: styles.coverLogo }) : null,
          h(PdfView, { key: "cover-brand-text" }, [
            text("NAKSHARIX", styles.coverBrandName, { key: "cover-name" }),
            text(labels[lang].brandSubtitle, styles.coverBrandSubtitle, { key: "cover-subtitle" })
          ])
        ]),
        h(PdfView, { key: "cover-divider", style: styles.coverDivider }),
        text(reportTypeLabel(pdfType, lang), styles.badge, { key: "badge" }),
        text(labels[lang].title, styles.coverTitle, { key: "cover-title" }),
        text(labels[lang].intro, styles.coverSubtitle, { key: "intro" })
      ]),
      h(PdfView, { key: "cover-grid", style: styles.grid2 }, [
        h(PdfView, { key: "summary-col", style: styles.col }, [section(labels[lang].summary, [
          row(labels[lang].nativeName, data.personDetails?.name),
          row(labels[lang].reportLanguage, languageName(lang)),
          row(labels[lang].generatedDate, generatedDate),
          row(labels[lang].lagna, ascendant),
          row(labels[lang].moonSign, moonSign),
          row(labels[lang].nakshatra, translateByCategory(data.avakahada?.nakshatra ?? data.panchang?.nakshatra, lang, "nakshatra"))
        ])]),
        h(PdfView, { key: "birth-col", style: styles.col }, [section(labels[lang].birth, birthRows)])
      ]),
      section(labels[lang].panchang, panchangRows)
    ]),
    makePage(`${labels[lang].charts} + ${labels[lang].planets}`, [
      h(PdfView, { key: "charts", style: styles.chartRow }, [
        chartPanel(h, text, PdfView, styles, PdfSvg, PdfRect, PdfLine, PdfText, labels[lang].d1Chart, data.d1Chart, lang),
        chartPanel(h, text, PdfView, styles, PdfSvg, PdfRect, PdfLine, PdfText, labels[lang].d9Chart, data.d9Chart, lang)
      ]),
      h(PdfView, { key: "chalit-note", style: styles.chartNote }, [
        text(labels[lang].chalitChart, styles.sectionTitle, { key: "title" }),
        text(Array.isArray(data.chalitChart) && data.chalitChart.length ? chartExplanation(lang) : chartUnavailable(labels[lang].chalitChart, lang), styles.mutedParagraph, { key: "note" })
      ]),
      section(labels[lang].charts, [
        paragraph(chartExplanation(lang), "chart-explanation", styles.mutedParagraph)
      ])
    ]),
    makePage(labels[lang].planets, [
      fixedSection(labels[lang].planets, [
        planetTable(h, text, PdfView, styles, data.planetaryPositions, lang),
        ...planetaryHighlights(data, lang).map((line, index) => paragraph(line, `planet-highlight-${index}`, index === 0 ? styles.goldParagraph : styles.mutedParagraph))
      ]),
      section(labels[lang].dasha, dashaSummary(h, text, PdfView, styles, data, lang)),
      section(labels[lang].chalitChart, chalitSummary(h, text, PdfView, styles, data, lang)),
      section(labels[lang].doshaAnalysis, doshaSummary(text, data, lang, styles)),
      section(labels[lang].yogaAnalysis, yogaSummary(text, data, lang, styles)),
      section(labels[lang].timingGuidance, [
        paragraph(timingGuidance(data, lang), "timing-guidance", styles.mutedParagraph)
      ])
    ]),
    makePage(labels[lang].detailedAnalysis, [
      section(labels[lang].lagnaSummary, [
        paragraph(safeInsight(data.predictions?.lagnaAnalysis, lang, "lagna"), "lagna"),
        row(labels[lang].lagna, ascendant),
        row(labels[lang].personalityStyle, safeInsight(data.predictions?.personalityAnalysis, lang, "personality")),
        ...bullets(personalityBullets(lang), "personality")
      ]),
      section(labels[lang].nakshatraSummary, [
        row(labels[lang].moonSign, moonSign),
        row(labels[lang].nakshatra, translateByCategory(data.avakahada?.nakshatra ?? data.panchang?.nakshatra, lang, "nakshatra")),
        paragraph(safeInsight(data.predictions?.nakshatraAnalysis, lang, "nakshatra"), "nakshatra"),
        paragraph(moonGuidance(lang, moonSign), "moon-guidance")
      ]),
      section(labels[lang].planetWiseInterpretation, planetInterpretationBlocks(data.planetaryPositions, lang).map((line, index) => paragraph(line, `planet-line-${index}`, index % 4 === 0 ? styles.goldParagraph : styles.paragraph))),
      section(labels[lang].houseWiseLifeAreas, houseInterpretationBlocks(data.d1Chart, lang).map((line, index) => paragraph(line, `house-line-${index}`, styles.paragraph))),
      section(labels[lang].careerFinance, [
        paragraph(`${labels[lang].careerOverview}: ${safeInsight(data.predictions?.careerAnalysis, lang, "career")}`, "career"),
        paragraph(`${labels[lang].finance}: ${safeInsight(data.predictions?.financeAnalysis, lang, "finance")}`, "finance"),
        ...bullets(careerFinanceBullets(lang), "career-finance")
      ]),
      section(labels[lang].relationshipMarriage, [
        paragraph(safeInsight(data.predictions?.marriageAnalysis, lang, "relationship"), "relationship"),
        ...bullets(relationshipBullets(lang), "relationship")
      ]),
      section(labels[lang].healthWellbeing, [
        paragraph(safeInsight(data.predictions?.healthAnalysis, lang, "health"), "health"),
        ...bullets(healthBullets(lang), "health")
      ]),
      section(labels[lang].generalRemedies, renderRemedies(text, data.remedies, lang, styles)),
      section(labels[lang].practicalGuidance, bullets(nextStepBullets(lang), "next-steps")),
      section(labels[lang].summary, [
        text(`${labels[lang].lagnaSummary}: ${safeInsight(data.predictions?.lagnaAnalysis, lang, "lagna")}`, styles.paragraph),
        text(`${labels[lang].nakshatraSummary}: ${safeInsight(data.predictions?.nakshatraAnalysis, lang, "nakshatra")}`, styles.paragraph),
        text(`${labels[lang].careerOverview}: ${safeInsight(data.predictions?.careerAnalysis, lang, "career")}`, styles.paragraph),
        text(`${labels[lang].relationshipOverview}: ${safeInsight(data.predictions?.marriageAnalysis, lang, "relationship")}`, styles.paragraph),
        text(`${labels[lang].healthOverview}: ${safeInsight(data.predictions?.healthAnalysis, lang, "health")}`, styles.paragraph),
        text(safeInsight(data.predictions?.aiSummary, lang, "ai"), styles.paragraph)
      ]),
      section(labels[lang].nextSteps, [paragraph(labels[lang].premiumCta, "premium-cta", styles.mutedParagraph)]),
      section(labels[lang].disclaimer, [paragraph(disclaimerText(lang), "disclaimer", styles.mutedParagraph)])
    ])
  ]);

  const stream = await pdf(document).toBuffer();
  const chunks: Buffer[] = [];
  for await (const chunk of stream as AsyncIterable<Buffer | Uint8Array | string>) {
    chunks.push(Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk));
  }
  const buffer = Buffer.concat(chunks);
  if (!buffer.length) throw new Error("Generated PDF buffer is empty");
  return buffer;
}

function page(
  h: PdfElementFactory,
  text: PdfTextFactory,
  Page: PdfComponent,
  View: PdfComponent,
  Image: PdfComponent,
  Text: PdfComponent,
  styles: PdfStyles,
  lang: Locale,
  title: string,
  generatedDate: string,
  logoSource: string | null,
  children: ReactElement[]
) {
  return h(Page, { key: title, size: "A4", style: styles.page }, [
    h(View, { key: "watermark", fixed: true, style: styles.watermark }, [
      logoSource ? h(Image, { key: "watermark-logo", src: logoSource, style: styles.watermarkLogo }) : null,
      text("NAKSHARIX", styles.watermarkText, { key: "watermark-name" }),
      text(labels[lang].brandSubtitle, styles.watermarkSubtext, { key: "watermark-subtitle" })
    ]),
    h(View, { key: "header", fixed: true, style: styles.header }, [
      h(View, { key: "brand", style: styles.brandBlock }, [
        logoSource ? h(Image, { key: "logo", src: logoSource, style: styles.logo }) : null,
        h(View, { key: "brand-texts", style: styles.brandTextBlock }, [
          text("NAKSHARIX", styles.brand, { key: "brand-text" }),
          text(labels[lang].brandSubtitle, styles.brandSubtitle, { key: "brand-subtitle" })
        ])
      ]),
      h(View, { key: "meta", style: styles.headerMeta }, [
        text(title, styles.headerTitle, { key: "header-title" }),
        text("naksharix.com", styles.site, { key: "site" })
      ])
    ]),
    text(title, styles.reportTitle, { key: "page-title" }),
    h(View, { key: "content", style: styles.content }, children),
    h(View, { key: "footer", fixed: true, style: styles.footer }, [
      text(labels[lang].generatedBy, styles.footerText, { key: "generated-by" }),
      text(generatedDate, styles.footerText, { key: "date" }),
      h(Text, {
        key: "page-number",
        fixed: true,
        style: pdfTextStyle(styles.pageCounter, lang),
        render: ({ pageNumber, totalPages }: { pageNumber: number; totalPages: number }) => `${labels[lang].pageLabel} ${pageNumber} / ${totalPages}`
      })
    ])
  ]);
}

function planetTable(h: PdfElementFactory, text: PdfTextFactory, View: PdfComponent, styles: PdfStyles, planets: unknown[], lang: Locale) {
  const rows: PlanetRow[] = Array.isArray(planets) && planets.length ? planets.map(toPlanetRow) : [{ planet: labels[lang].notAvailable }];
  return h(View, { key: "planet-table" }, [
    h(View, { key: "head", style: styles.tableHeader }, [
      text(labels[lang].planet, styles.cellPlanet, { key: "planet" }),
      text(labels[lang].sign, styles.cellSign, { key: "sign" }),
      text(labels[lang].house, styles.cellSmall, { key: "house" }),
      text(labels[lang].degree, styles.cellSmall, { key: "degree" }),
      text(labels[lang].nakshatra, styles.cellWide, { key: "nakshatra" }),
      text(labels[lang].pada, styles.cellSmall, { key: "pada" })
    ]),
    ...rows.map((planet, index) => h(View, { key: `planet-${index}`, style: styles.tableRow }, [
      text(translatePlanetValue(planet?.planet, lang), styles.cellPlanet, { key: "planet" }),
      text(translateSignValue(planet?.sign, lang), styles.cellSign, { key: "sign" }),
      text(planet?.house, styles.cellSmall, { key: "house" }),
      text(planet?.degree, styles.cellSmall, { key: "degree" }),
      text(translateByCategory(planet?.nakshatra, lang, "nakshatra"), styles.cellWide, { key: "nakshatra" }),
      text(planet?.pada, styles.cellSmall, { key: "pada" })
    ]))
  ]);
}

function dashaTable(h: PdfElementFactory, text: PdfTextFactory, View: PdfComponent, styles: PdfStyles, dashas: unknown[], lang: Locale) {
  const rows: DashaRow[] = Array.isArray(dashas) ? dashas.map(toDashaRow).filter((dasha) => !isUnavailableText(safeText(dasha?.planet ?? dasha?.name, lang))) : [];
  if (!rows.length) return h(View, { key: "dasha-table" }, [text(labels[lang].dashaUnavailable, styles.paragraph, { key: "dasha-note" })]);
  return h(View, { key: "dasha-table" }, rows.map((dasha, index) => h(View, { key: `dasha-${index}`, style: styles.row }, [
    text(translatePlanetValue(dasha?.planet ?? dasha?.name, lang), styles.key, { key: "planet" }),
    text(formatDateRange(dasha?.startDate ?? dasha?.startsAt, dasha?.endDate ?? dasha?.endsAt, lang), styles.value, { key: "dates" })
  ])));
}

function dashaSummary(h: PdfElementFactory, text: PdfTextFactory, View: PdfComponent, styles: PdfStyles, data: PdfData, lang: Locale) {
  const calculated = data.calculatedDasha;
  if (!calculated?.available) {
    return [text(calculated?.note ?? labels[lang].dashaUnavailable, styles.paragraph, { key: "dasha-note" })];
  }
  return [
    h(View, { key: "current-maha", style: styles.row }, [
      text(labels[lang].currentMahadasha, styles.key, { key: "k" }),
      text(dashaPeriodLabel(calculated.currentMahadasha, lang), styles.value, { key: "v" })
    ]),
    h(View, { key: "current-antar", style: styles.row }, [
      text(labels[lang].currentAntardasha, styles.key, { key: "k" }),
      text(dashaPeriodLabel(calculated.currentAntardasha, lang), styles.value, { key: "v" })
    ]),
    h(View, { key: "balance", style: styles.row }, [
      text(labels[lang].dashaBalance, styles.key, { key: "k" }),
      text(typeof calculated.birthBalanceYears === "number" ? `${calculated.birthBalanceYears.toFixed(2)} years` : labels[lang].notAvailable, styles.value, { key: "v" })
    ]),
    text(labels[lang].dashaTimeline, styles.goldParagraph, { key: "timeline-title" }),
    dashaTable(h, text, View, styles, data.vimshottariDasha.slice(0, 5), lang)
  ];
}

function chalitSummary(h: PdfElementFactory, text: PdfTextFactory, View: PdfComponent, styles: PdfStyles, data: PdfData, lang: Locale) {
  const chalit = data.chalitAnalysis;
  if (!chalit?.available) return [text(chalit?.note ?? chartUnavailable(labels[lang].chalitChart, lang), styles.paragraph, { key: "chalit-note" })];
  const changed = chalit.placements.filter((placement) => placement.changed);
  const rows = (changed.length ? changed : chalit.placements.slice(0, 6)).slice(0, 8);
  return [
    h(View, { key: "method", style: styles.row }, [
      text(labels[lang].chalitMethod, styles.key, { key: "k" }),
      text(translateEngineText(chalit.method, lang), styles.value, { key: "v" })
    ]),
    ...rows.map((placement, index) => h(View, { key: `chalit-${index}`, style: styles.row }, [
      text(translatePlanetValue(placement.planet, lang), styles.key, { key: "k" }),
      text(`${labels[lang].d1House}: ${placement.d1House ?? labels[lang].dash} | ${labels[lang].chalitHouse}: ${placement.chalitHouse ?? labels[lang].dash} | ${translateEngineText(placement.note, lang)}`, styles.value, { key: "v" })
    ]))
  ];
}

function doshaSummary(text: PdfTextFactory, data: PdfData, lang: Locale, styles: PdfStyles) {
  const dosha = data.doshaAnalysis;
  return [
    text(`${labels[lang].manglikStatus}: ${safeText(dosha?.manglik?.severity ?? data.doshas.manglik.severity, lang)}`, styles.goldParagraph, { key: "manglik-title" }),
    text(translateEngineText(dosha?.manglik?.summary ?? data.doshas.manglik.summary, lang), styles.paragraph, { key: "manglik-summary" }),
    text(`${labels[lang].kaalSarpStatus}: ${safeText(dosha?.kaalSarp?.severity ?? data.doshas.kaalSarp.severity, lang)}`, styles.goldParagraph, { key: "kaal-title" }),
    text(translateEngineText(dosha?.kaalSarp?.summary ?? data.doshas.kaalSarp.summary, lang), styles.paragraph, { key: "kaal-summary" }),
    ...(dosha?.notes ?? []).slice(0, 2).map((note, index) => text(translateEngineText(note, lang), styles.mutedParagraph, { key: `dosha-note-${index}` }))
  ];
}

function yogaSummary(text: PdfTextFactory, data: PdfData, lang: Locale, styles: PdfStyles) {
  const yogas = data.yogaAnalysis?.detected ?? [];
  if (!yogas.length) return [text(translateEngineText(data.yogaAnalysis?.note ?? labels[lang].noYoga, lang), styles.paragraph, { key: "no-yoga" })];
  return yogas.slice(0, 6).flatMap((yoga, index) => [
    text(`${labels[lang].detectedYogas}: ${translateYogaName(yoga.name, lang)}`, styles.goldParagraph, { key: `yoga-name-${index}` }),
    text(`${translateEngineText(yoga.basis, lang)} ${translateEngineText(yoga.interpretation, lang)}`, styles.paragraph, { key: `yoga-copy-${index}` })
  ]);
}

function renderRemedies(text: PdfTextFactory, remedies: unknown[], lang: Locale, styles: PdfStyles) {
  const cleaned = Array.isArray(remedies)
    ? remedies.map((remedy) => safeText(remedy, lang)).filter((remedy) => !isUnavailableText(remedy))
    : [];
  const items = cleaned.length ? cleaned : fallbackRemedies(lang);
  return items.map((remedy, index) => text(`• ${remedy}`, styles.paragraph, { key: `remedy-${index}` }));
}

function chartPanel(
  h: PdfElementFactory,
  text: PdfTextFactory,
  View: PdfComponent,
  styles: PdfStyles,
  Svg: PdfComponent,
  Rect: PdfComponent,
  Line: PdfComponent,
  SvgText: PdfComponent,
  title: string,
  houses: unknown[],
  lang: Locale
) {
  void Svg;
  void Rect;
  void Line;
  void SvgText;
  return h(View, { key: title, style: styles.chartBox }, [
    text(title, styles.chartTitle, { key: "title" }),
    Array.isArray(houses) && houses.length ? chartGrid(h, text, View, styles, houses, lang) : text(chartUnavailable(title, lang), styles.mutedParagraph, { key: "empty" })
  ]);
}

function chartGrid(
  h: PdfElementFactory,
  text: PdfTextFactory,
  View: PdfComponent,
  styles: PdfStyles,
  houses: unknown[],
  lang: Locale
) {
  const normalized = houses.map(toChartHouse);
  return h(View, { key: "chart-grid", style: styles.chartGrid, wrap: false }, Array.from({ length: 12 }, (_, index) => {
    const houseNumber = index + 1;
    const house = normalized.find((item) => Number(item.house) === houseNumber) ?? { house: houseNumber, planets: [] };
    const sign = chartSignLabel(house, lang);
    const planetLines = chartPlanetLines(planetLabels(house, lang), lang);

    return h(View, { key: `house-${houseNumber}`, style: styles.chartHouseCard }, [
      text(`${labels[lang].house} ${houseNumber}`, styles.chartHouseHeader, { key: "house" }),
      text(sign, styles.chartHouseSign, { key: "sign" }),
      ...planetLines.map((line, lineIndex) => text(line, styles.chartPlanetLine, { key: `planets-${lineIndex}` }))
    ]);
  }));
}

function chartSignLabel(house: ChartHouse, lang: Locale) {
  const sign = translateSignValue(house.sign, lang);
  if (!isUnavailableText(sign)) return sign;
  const signNumber = safeText(house.signNumber, lang);
  return isUnavailableText(signNumber) ? labels[lang].dash : signNumber;
}

function chartPlanetLines(planets: string[], lang: Locale) {
  const visible = visibleChartPlanetLabels(planets);
  if (!visible.length) return [labels[lang].dash];
  if (visible.length <= 2) return [visible.join("  ")];
  if (visible.length === 3) return [`${visible[0]}  ${visible[1]}`, visible[2]];
  if (visible.length === 4) return [`${visible[0]}  ${visible[1]}`, `${visible[2]}  ${visible[3]}`];
  return [visible.slice(0, 3).join("  "), visible.slice(3, 6).join("  ")];
}

function visibleChartPlanetLabels(planets: string[]) {
  if (planets.length <= 6) return planets;
  return [...planets.slice(0, 5), `+${planets.length - 5}`];
}

function pdfTextStyle(style: unknown, lang: Locale) {
  const fontPatch = lang === "hi" ? { fontFamily: PDF_FONT_FAMILY, letterSpacing: 0 } : { fontFamily: PDF_FONT_FAMILY };
  if (Array.isArray(style)) return [...style, fontPatch];
  if (style && typeof style === "object") return { ...(style as Record<string, unknown>), ...fontPatch };
  return fontPatch;
}

function registerPdfFonts(Font: PdfFontRegistry) {
  if (pdfFontsRegistered) return;
  const fontDir = path.join(process.cwd(), "public", "fonts");
  Font.registerHyphenationCallback?.((word) => [word]);
  Font.register({
    family: PDF_FONT_FAMILY,
    fonts: [
      { src: path.join(fontDir, "NotoSansDevanagari-Regular.ttf"), fontWeight: 400 },
      { src: path.join(fontDir, "NotoSansDevanagari-Bold.ttf"), fontWeight: 700 },
      { src: path.join(fontDir, "NotoSansDevanagari-Bold.ttf"), fontWeight: 800 }
    ]
  });
  pdfFontsRegistered = true;
}

function loadPdfLogoSource() {
  if (pdfLogoDataUri !== undefined) return pdfLogoDataUri;
  try {
    if (!fs.existsSync(PDF_LOGO_PATH)) {
      console.warn("[Naksharix PDF] Logo asset not found for PDF branding", { path: PDF_LOGO_PATH });
      pdfLogoDataUri = null;
      return pdfLogoDataUri;
    }
    const bytes = fs.readFileSync(PDF_LOGO_PATH);
    pdfLogoDataUri = `data:${PDF_LOGO_MIME};base64,${bytes.toString("base64")}`;
    return pdfLogoDataUri;
  } catch (error) {
    console.warn("[Naksharix PDF] Unable to embed PDF logo asset", { path: PDF_LOGO_PATH, error });
    pdfLogoDataUri = null;
    return pdfLogoDataUri;
  }
}

function planetLabels(house: ChartHouse, lang: Locale) {
  const planets = Array.isArray(house?.planets) ? house.planets : [];
  return planets.map((planet) => shortPlanet(typeof planet === "string" ? planet : planet.planet ?? planet.name, lang)).filter(Boolean);
}

function toPlanetRow(value: unknown): PlanetRow {
  return isRecord(value) ? value : { planet: safeText(value, "en") };
}

function toDashaRow(value: unknown): DashaRow {
  return isRecord(value) ? value : { planet: safeText(value, "en") };
}

function toChartHouse(value: unknown): ChartHouse {
  if (!isRecord(value)) return { planets: [] };
  const planets = Array.isArray(value.planets) ? value.planets.map(toChartPlanet) : [];
  return { house: value.house, sign: value.sign, signNumber: value.signNumber, planets };
}

function toChartPlanet(value: unknown): string | ChartPlanet {
  if (typeof value === "string") return value;
  if (!isRecord(value)) return safeText(value, "en");
  return { planet: value.planet, name: value.name };
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function shortPlanet(planet: unknown, lang: Locale) {
  const raw = translatePlanetValue(planet, lang);
  const map: Record<string, string> = {
    Sun: "Su", Moon: "Mo", Mars: "Ma", Mercury: "Me", Jupiter: "Ju", Venus: "Ve", Saturn: "Sa", Rahu: "Ra", Ketu: "Ke", Ascendant: "As", Lagna: "As",
    सूर्य: "सू", चंद्र: "चं", मंगल: "मं", बुध: "बु", गुरु: "गु", शुक्र: "शु", शनि: "श", राहु: "रा", केतु: "के", लग्न: "ल",
    Surya: "Su", Chandra: "Ch", Mangal: "Ma", Budh: "Bu", Guru: "Gu", Shukra: "Sh", Shani: "Sa"
  };
  return map[raw] ?? raw.slice(0, 3);
}

function safeText(value: unknown, lang: Locale): string {
  if (value === null || value === undefined || value === "") return labels[lang].notAvailable;
  if (typeof value === "string" || typeof value === "number" || typeof value === "boolean") return normalizeDisplayText(String(value), lang);
  if (Array.isArray(value)) {
    const items = value.map((item) => safeText(item, lang)).filter((item) => !isUnavailableText(item));
    return items.length ? items.join(", ") : labels[lang].notAvailable;
  }
  if (typeof value === "object") {
    const obj = value as Record<string, unknown>;
    if ("name" in obj) return safeText(obj.name, lang);
    if ("label" in obj) return safeText(obj.label, lang);
    if ("value" in obj) return safeText(obj.value, lang);
    if ("sign" in obj) return safeText(obj.sign, lang);
    if ("house" in obj) return safeText(obj.house, lang);
    if ("planet" in obj) return safeText(obj.planet, lang);
    return labels[lang].notAvailable;
  }
  return normalizeDisplayText(String(value), lang);
}

function translatePlanetValue(value: unknown, lang: Locale) {
  const raw = safeText(value, lang);
  if (isUnavailableText(raw)) return labels[lang].notAvailable;
  return translatePlanet(raw, lang) || raw;
}

function translateSignValue(value: unknown, lang: Locale) {
  const raw = safeText(value, lang);
  if (isUnavailableText(raw)) return labels[lang].notAvailable;
  return translateSign(raw, lang) || raw;
}

function translateByCategory(value: unknown, lang: Locale, category: AstroValueCategory) {
  const raw = safeText(value, lang);
  if (isUnavailableText(raw)) return labels[lang].notAvailable;
  return translateAstroValue(raw, lang, category) || raw;
}

function translateYogaName(value: unknown, lang: Locale) {
  const raw = safeText(value, lang);
  if (isUnavailableText(raw)) return labels[lang].notAvailable;
  const names: Record<string, Record<Locale, string>> = {
    "Budh Aditya Yoga": { en: "Budh Aditya Yoga", hi: "बुध आदित्य योग", hinglish: "Budh Aditya Yoga" },
    "Gaja Kesari Yoga": { en: "Gaja Kesari Yoga", hi: "गजकेसरी योग", hinglish: "Gaja Kesari Yoga" },
    "Chandra Mangal Yoga": { en: "Chandra Mangal Yoga", hi: "चंद्र मंगल योग", hinglish: "Chandra Mangal Yoga" },
    "Ruchaka Yoga": { en: "Ruchaka Yoga", hi: "रुचक योग", hinglish: "Ruchaka Yoga" },
    "Bhadra Yoga": { en: "Bhadra Yoga", hi: "भद्र योग", hinglish: "Bhadra Yoga" },
    "Hamsa Yoga": { en: "Hamsa Yoga", hi: "हंस योग", hinglish: "Hamsa Yoga" },
    "Malavya Yoga": { en: "Malavya Yoga", hi: "मालव्य योग", hinglish: "Malavya Yoga" },
    "Shasha Yoga": { en: "Shasha Yoga", hi: "शश योग", hinglish: "Shasha Yoga" }
  };
  return names[raw]?.[lang] ?? raw;
}

function translateEngineText(value: unknown, lang: Locale) {
  const raw = safeText(value, lang);
  if (isUnavailableText(raw)) return labels[lang].notAvailable;
  if (lang !== "hi") return raw;
  const exact: Record<string, string> = {
    "Equal-house Chalit from available ascendant and planetary longitude data": "उपलब्ध लग्न और ग्रह देशांतर डेटा के आधार पर समान-भाव चलित गणना",
    "Equal-house Chalit from ascendant longitude": "लग्न देशांतर के आधार पर समान-भाव चलित गणना",
    "Needs full chart, strength, aspects, and dasha review before final judgment.": "अंतिम निर्णय से पहले पूरी कुंडली, ग्रह बल, दृष्टि और दशा समीक्षा आवश्यक है।"
  };
  if (exact[raw]) return exact[raw];
  return raw
    .replace(/\bBudh Aditya Yoga\b/g, "बुध आदित्य योग")
    .replace(/\bGaja Kesari Yoga\b/g, "गजकेसरी योग")
    .replace(/\bChandra Mangal Yoga\b/g, "चंद्र मंगल योग")
    .replace(/\bRuchaka Yoga\b/g, "रुचक योग")
    .replace(/\bBhadra Yoga\b/g, "भद्र योग")
    .replace(/\bHamsa Yoga\b/g, "हंस योग")
    .replace(/\bMalavya Yoga\b/g, "मालव्य योग")
    .replace(/\bShasha Yoga\b/g, "शश योग")
    .replace(/\bSun\b/g, "सूर्य")
    .replace(/\bMoon\b/g, "चंद्र")
    .replace(/\bMars\b/g, "मंगल")
    .replace(/\bMercury\b/g, "बुध")
    .replace(/\bJupiter\b/g, "गुरु")
    .replace(/\bVenus\b/g, "शुक्र")
    .replace(/\bSaturn\b/g, "शनि")
    .replace(/\bRahu\b/g, "राहु")
    .replace(/\bKetu\b/g, "केतु");
}

function formatDateRange(start: unknown, end: unknown, lang: Locale) {
  const startText = safeText(start, lang);
  const endText = safeText(end, lang);
  if (isUnavailableText(startText) && isUnavailableText(endText)) return labels[lang].dashaUnavailable;
  if (isUnavailableText(startText)) return endText;
  if (isUnavailableText(endText)) return startText;
  return `${startText} - ${endText}`;
}

function dashaPeriodLabel(period: DashaRow | undefined, lang: Locale) {
  if (!period) return labels[lang].notAvailable;
  return `${translatePlanetValue(period.planet ?? period.name, lang)} (${formatDateRange(period.startDate ?? period.startsAt, period.endDate ?? period.endsAt, lang)})`;
}

function safeInsight(value: unknown, lang: Locale, section: InsightSection) {
  const text = safeText(value, lang);
  if (!isUnavailableText(text) && !looksEnglishOnlyFallback(text, lang) && !(lang === "hi" && containsLatinProse(text))) return text;
  return insightFallbacks[lang][section];
}

function normalizeDisplayText(value: string, lang: Locale) {
  const text = value.trim().normalize("NFC");
  if (!text || isUnavailableText(text) || isRawOutput(text)) return labels[lang].notAvailable;
  const unavailableWords = "(?:Not available|Available nahi hai|उपलब्ध नहीं|null|undefined|\\[object Object\\])";
  const repeatedFallback = new RegExp(`^(?:${unavailableWords})(?:\\s*(?:-|,|/)\\s*${unavailableWords}|\\s+${unavailableWords})+$`, "i");
  if (repeatedFallback.test(text)) return labels[lang].notAvailable;
  return text.replace(new RegExp(`${unavailableWords}(?:\\s+${unavailableWords})+`, "gi"), labels[lang].notAvailable);
}

function isUnavailableText(value: string) {
  return /^(?:not available|available nahi hai|उपलब्ध नहीं|null|undefined|\[object Object\])$/i.test(value.trim());
}

function isRawOutput(value: string) {
  const text = value.trim();
  return (text.startsWith("{") && text.endsWith("}")) || (text.startsWith("[") && text.endsWith("]")) || text.includes("[object Object]");
}

function looksEnglishOnlyFallback(value: string, lang: Locale) {
  if (lang === "en") return false;
  return /not available|currently unavailable|review the chart|AI interpretation is currently limited/i.test(value);
}

function containsLatinProse(value: string) {
  return /[A-Za-z]{4,}/.test(value);
}

function chartUnavailable(title: string, lang: Locale) {
  if (title === labels[lang].chalitChart) {
    if (lang === "hi") return "चलित चार्ट डेटा अभी उपलब्ध नहीं है। D1 और D9 चार्ट के आधार पर उपलब्ध संकेत देखें।";
    if (lang === "hinglish") return "Chalit chart data abhi available nahi hai. D1 aur D9 chart ke available signals dekhein.";
    return "Chalit chart data is currently unavailable. Review the available D1 and D9 chart signals.";
  }
  return labels[lang].cleanUnavailable;
}

function languageName(lang: Locale) {
  if (lang === "hi") return "हिंदी";
  if (lang === "hinglish") return "Hinglish";
  return "English";
}

function reportTypeLabel(pdfType: "FREE" | "PREMIUM", lang: Locale) {
  return pdfType === "FREE" ? labels[lang].freeReport : labels[lang].premiumReport;
}

function translateGender(value: unknown, lang: Locale) {
  const raw = safeText(value, "en").toLowerCase();
  if (isUnavailableText(raw)) return labels[lang].notAvailable;
  if (raw === "male" || raw === "m") {
    if (lang === "hi") return "पुरुष";
    if (lang === "hinglish") return "Purush";
    return "Male";
  }
  if (raw === "female" || raw === "f") {
    if (lang === "hi") return "स्त्री";
    if (lang === "hinglish") return "Stree";
    return "Female";
  }
  if (raw === "other" || raw === "others") {
    if (lang === "hi") return "अन्य";
    if (lang === "hinglish") return "Anya";
    return "Other";
  }
  return safeText(value, lang);
}

function chartExplanation(lang: Locale) {
  if (lang === "hi") return "D1 चार्ट जीवन की मूल संरचना और व्यक्तित्व संकेत देता है; D9 नवांश धर्म, संबंध और गहराई समझने में मदद करता है। चलित चार्ट उपलब्ध न होने पर उसके स्थान पर एक स्पष्ट नोट दिया गया है।";
  if (lang === "hinglish") return "D1 chart life structure aur visible personality ko dikhata hai; D9 navamsa dharma, relationship aur deeper context samajhne me help karta hai. Chalit chart available na ho to clean note diya gaya hai.";
  return "The D1 chart reflects life structure and visible personality; D9 supports deeper dharma, relationship, and inner context. If Chalit data is unavailable, the report shows one clean note instead.";
}

function planetaryHighlights(data: PdfData, lang: Locale) {
  const planets = Array.isArray(data.planetaryPositions) ? data.planetaryPositions.map(toPlanetRow) : [];
  const houseCounts = new Map<string, number>();
  planets.forEach((planet) => {
    const house = safeText(planet.house, lang);
    if (!isUnavailableText(house)) houseCounts.set(house, (houseCounts.get(house) ?? 0) + 1);
  });
  const strongestHouse = Array.from(houseCounts.entries()).sort((a, b) => b[1] - a[1])[0];
  const lagna = translateSignValue(data.avakahada?.ascendant, lang);
  const moon = translateSignValue(data.avakahada?.moonSign, lang);
  const nakshatra = translateByCategory(data.avakahada?.nakshatra ?? data.panchang?.nakshatra, lang, "nakshatra");
  if (lang === "hi") {
    return [
      `ग्रह संकेत: लग्न ${lagna}, चंद्र राशि ${moon}, नक्षत्र ${nakshatra}`,
      strongestHouse ? `मुख्य भाव जोर: भाव ${strongestHouse[0]} में ${strongestHouse[1]} ग्रह दिख रहे हैं। इसे पूरे चार्ट संदर्भ के साथ पढ़ें।` : "मुख्य भाव जोर: उपलब्ध ग्रह स्थिति से कोई स्पष्ट ग्रह समूह नहीं दिखता।",
      "यह सारांश केवल उपलब्ध ग्रह स्थिति पर आधारित है; इसे दशा, दृष्टि और योग के साथ मिलाकर समझना चाहिए।"
    ];
  }
  if (lang === "hinglish") {
    return [
      `Planetary highlights: Lagna ${lagna}, Moon sign ${moon}, Nakshatra ${nakshatra}`,
      strongestHouse ? `Main house emphasis: House ${strongestHouse[0]} me ${strongestHouse[1]} grah dikh rahe hain. Isse full chart context ke saath padhein.` : "Main house emphasis: available positions se clear planet cluster nahi dikh raha.",
      "Yeh summary available planetary positions par based hai; dasha, aspects aur yogas ke saath read karna best hai."
    ];
  }
  return [
    `Planetary highlights: Lagna ${lagna}, Moon sign ${moon}, Nakshatra ${nakshatra}`,
    strongestHouse ? `Main house emphasis: house ${strongestHouse[0]} contains ${strongestHouse[1]} visible planet placements. Read it with the full chart context.` : "Main house emphasis: no clear planet cluster appears in the available positions.",
    "This summary uses available planetary positions only; timing, aspects, and yogas should be reviewed together."
  ];
}

function personalityBullets(lang: Locale) {
  return {
    en: ["Strengths: analytical thinking, observation, and steady refinement.", "Growth areas: avoid overthinking and keep decisions tied to clear priorities."],
    hi: ["शक्तियां: विश्लेषणात्मक सोच, अवलोकन और निरंतर सुधार।", "विकास क्षेत्र: अधिक सोचने से बचें और निर्णयों को स्पष्ट प्राथमिकताओं से जोड़ें।"],
    hinglish: ["Strengths: analytical thinking, observation aur steady refinement.", "Growth areas: overthinking se bachein aur decisions ko clear priorities se jodein."]
  }[lang];
}

function moonGuidance(lang: Locale, moonSign: string) {
  if (lang === "hi") return `${labels.hi.moonSign} ${moonSign} मन की लय, भावनात्मक प्रतिक्रिया और सहज निर्णयों को समझने में मदद करता है। शांत संवाद और स्थिर दिनचर्या भावनात्मक संतुलन को मजबूत करती है।`;
  if (lang === "hinglish") return `${labels.hinglish.moonSign} ${moonSign} mind rhythm, emotional response aur instinctive decisions ko samajhne me help karta hai. Calm communication aur steady routine balance banate hain.`;
  return `${labels.en.moonSign} ${moonSign} helps explain emotional rhythm, instinctive reactions, and mental habits. Calm communication and steady routine strengthen balance.`;
}

function careerFinanceBullets(lang: Locale) {
  return {
    en: ["Choose fewer goals and execute them deeply instead of scattering effort.", "Track expenses, commitments, and risk before making major financial moves.", "Skill-building, consistency, and clean communication improve professional momentum."],
    hi: ["बिखरे हुए अवसरों के बजाय कम लक्ष्यों को चुनकर गहराई से काम करें।", "बड़े वित्तीय निर्णय से पहले खर्च, प्रतिबद्धता और जोखिम को स्पष्ट रूप से देखें।", "कौशल-विकास, निरंतरता और साफ संवाद करियर गति को बेहतर बनाते हैं।"],
    hinglish: ["Scattered effort ke bajay fewer goals choose karke deeply execute karein.", "Major financial move se pehle expenses, commitments aur risk clearly review karein.", "Skill-building, consistency aur clean communication professional momentum improve karte hain."]
  }[lang];
}

function relationshipBullets(lang: Locale) {
  return {
    en: ["Treat marriage timing as a combined chart, dasha, Venus, Mars, Moon, and seventh-house review.", "Keep communication steady; avoid making permanent decisions from temporary emotions.", "Family alignment improves when expectations are spoken early and respectfully."],
    hi: ["विवाह समय को संयुक्त रूप से चार्ट, दशा, शुक्र, मंगल, चंद्र और सप्तम भाव से समझना चाहिए।", "संवाद स्थिर रखें; अस्थायी भावनाओं से स्थायी निर्णय न लें।", "अपेक्षाएं समय पर और सम्मानपूर्वक स्पष्ट करने से परिवारिक सामंजस्य बढ़ता है।"],
    hinglish: ["Marriage timing ko chart, dasha, Venus, Mars, Moon aur seventh house ke combined review se samjhein.", "Communication steady rakhein; temporary emotions se permanent decisions na lein.", "Expectations early aur respectfully clear karne se family alignment improve hota hai."]
  }[lang];
}

function healthBullets(lang: Locale) {
  return {
    en: ["Keep sleep, hydration, movement, and food rhythm consistent.", "Use astrology as a reflective wellness signal, not as medical diagnosis.", "Seek professional care for any health concern that feels persistent or serious."],
    hi: ["नींद, जल सेवन, हलचल और भोजन की लय नियमित रखें।", "ज्योतिषीय संकेतों को आत्मचिंतन के रूप में लें, चिकित्सा निदान के रूप में नहीं।", "लगातार या गंभीर स्वास्थ्य चिंता में विशेषज्ञ चिकित्सा सलाह लें।"],
    hinglish: ["Sleep, hydration, movement aur food rhythm consistent rakhein.", "Astrology ko reflective wellness signal samjhein, medical diagnosis nahi.", "Persistent ya serious health concern me professional care lein."]
  }[lang];
}

function timingGuidance(data: PdfData, lang: Locale) {
  if (data.calculatedDasha?.available) {
    if (lang === "hi") return "वर्तमान महादशा और अंतर्दशा को समय-संदर्भ के रूप में देखें, लेकिन अंतिम निर्णय के लिए पूरी कुंडली, गोचर और व्यावहारिक परिस्थिति को साथ में समझें।";
    if (lang === "hinglish") return "Current Mahadasha aur Antardasha ko timing context ke roop mein dekhein, lekin final decision ke liye full chart strength, transits aur practical situation ko saath mein samjhein.";
    return "Use the current Mahadasha and Antardasha as timing context, but combine them with full chart strength, transits, and practical circumstances.";
  }
  if (lang === "hi") return "जब सटीक दशा उपलब्ध न हो, तब समय संबंधी निष्कर्षों को अंतिम भविष्यवाणी न मानें। उपलब्ध ग्रह स्थिति, लग्न, चंद्र राशि और व्यवहारिक परिस्थिति को मिलाकर निर्णय लें।";
  if (lang === "hinglish") return "Jab exact dasha available na ho, timing conclusions ko final prediction na samjhein. Available grah position, lagna, moon sign aur practical situation ko combine karke decision lein.";
  return "When exact dasha data is unavailable, timing notes should not be treated as final prediction. Combine available planetary positions, lagna, moon sign, and practical circumstances.";
}

function nextStepBullets(lang: Locale) {
  return {
    en: ["Review the lagna, Moon sign, and strongest repeated themes first.", "Use remedies gently: prayer, discipline, service, and reflection.", "Upgrade only if you need deeper timing, yogas, dosha notes, and expanded context."],
    hi: ["सबसे पहले लग्न, चंद्र राशि और दोहराए गए प्रमुख संकेतों की समीक्षा करें।", "उपायों को संतुलित रखें: प्रार्थना, अनुशासन, सेवा और आत्मचिंतन।", "गहरा समय विश्लेषण, योग, दोष नोट्स और विस्तृत संदर्भ चाहिए तभी अपग्रेड करें।"],
    hinglish: ["Sabse pehle lagna, Moon sign aur repeated themes review karein.", "Remedies gentle rakhein: prayer, discipline, service aur reflection.", "Deeper timing, yogas, dosha notes aur expanded context chahiye tabhi upgrade karein."]
  }[lang];
}

function disclaimerText(lang: Locale) {
  if (lang === "hi") return "यह रिपोर्ट आत्मचिंतन, योजना और आध्यात्मिक मार्गदर्शन के उद्देश्य से बनाई गई है। यह चिकित्सा, कानूनी, वित्तीय या मानसिक स्वास्थ्य सलाह का विकल्प नहीं है। किसी भी महत्वपूर्ण निर्णय से पहले योग्य विशेषज्ञ से सलाह लें।";
  if (lang === "hinglish") return "Yeh report reflection, planning aur spiritual guidance ke liye bani hai. Yeh medical, legal, financial ya mental-health advice ka replacement nahi hai. Important decisions se pehle qualified expert se salah lein.";
  return "This report is created for reflection, planning, and spiritual guidance. It does not replace medical, legal, financial, or mental-health advice. Please consult a qualified expert before major decisions.";
}

function planetInterpretationBlocks(planets: unknown[], lang: Locale) {
  const rows = Array.isArray(planets) ? planets.map(toPlanetRow) : [];
  const byPlanet = new Map(rows.map((planet) => [String(planet.planet ?? ""), planet]));
  const order = ["Sun", "Moon", "Mars", "Mercury", "Jupiter", "Venus", "Saturn", "Rahu", "Ketu"];
  return order.flatMap((planetName) => {
    const planet = byPlanet.get(planetName) ?? { planet: planetName };
    const translatedPlanet = translatePlanetValue(planet.planet, lang);
    const sign = translateSignValue(planet.sign, lang);
    const house = safeText(planet.house, lang);
    const nakshatra = translateByCategory(planet.nakshatra, lang, "nakshatra");
    return planetCopy(lang, planetName, translatedPlanet, sign, house, nakshatra);
  });
}

function planetCopy(lang: Locale, planetKey: string, planet: string, sign: string, house: string, nakshatra: string) {
  const role = planetRoleCopy[lang][planetKey] ?? planetRoleCopy[lang].Sun;
  if (lang === "hi") {
    return [
      `${planet}: ${labels.hi.sign} ${sign}, ${labels.hi.house} ${house}, ${labels.hi.nakshatra} ${nakshatra}`,
      role.meaning,
      `${labels.hi.positivePotential}: ${role.positive}`,
      `${labels.hi.cautionGrowth}: ${role.caution}`
    ];
  }
  if (lang === "hinglish") {
    return [
      `${planet}: ${labels.hinglish.sign} ${sign}, ${labels.hinglish.house} ${house}, ${labels.hinglish.nakshatra} ${nakshatra}`,
      role.meaning,
      `${labels.hinglish.positivePotential}: ${role.positive}`,
      `${labels.hinglish.cautionGrowth}: ${role.caution}`
    ];
  }
  return [
    `${planet}: ${labels.en.sign} ${sign}, ${labels.en.house} ${house}, ${labels.en.nakshatra} ${nakshatra}`,
    role.meaning,
    `${labels.en.positivePotential}: ${role.positive}`,
    `${labels.en.cautionGrowth}: ${role.caution}`
  ];
}

const planetRoleCopy: Record<Locale, Record<string, { meaning: string; positive: string; caution: string }>> = {
  en: {
    Sun: {
      meaning: "The Sun describes identity, confidence, vitality, authority, and the way the native expresses personal purpose.",
      positive: "Its sign and house show where self-expression, leadership, and clarity can become visible.",
      caution: "Balance pride with humility and avoid forcing recognition before the work is mature."
    },
    Moon: {
      meaning: "The Moon describes emotions, mind, habits, motherly influence, and the native's instinctive response pattern.",
      positive: "Its placement helps understand emotional needs, public response, and the rhythm that restores inner security.",
      caution: "Avoid reacting from temporary moods; steady routine and calm communication help."
    },
    Mars: {
      meaning: "Mars shows courage, action, initiative, physical energy, and the way conflict or competition is handled.",
      positive: "Its placement can support decisive effort, focused ambition, and the ability to act under pressure.",
      caution: "Channel anger and urgency into disciplined action rather than impulsive decisions."
    },
    Mercury: {
      meaning: "Mercury relates to communication, logic, learning, trade, analysis, and decision-making style.",
      positive: "Its position supports skill-building, writing, speaking, negotiation, and practical intelligence.",
      caution: "Avoid over-analysis, scattered attention, and using words carelessly in sensitive matters."
    },
    Jupiter: {
      meaning: "Jupiter represents wisdom, teachers, guidance, ethics, growth, faith, and long-range understanding.",
      positive: "Its placement highlights where counsel, learning, generosity, and dharmic growth can expand life.",
      caution: "Growth is strongest when optimism is paired with discipline and realistic commitments."
    },
    Venus: {
      meaning: "Venus shows relationships, harmony, comfort, aesthetics, pleasure, values, and the ability to receive support.",
      positive: "Its placement reveals how love, art, diplomacy, and quality of life can be cultivated.",
      caution: "Avoid confusing comfort with avoidance; real harmony needs honest communication."
    },
    Saturn: {
      meaning: "Saturn represents discipline, responsibility, structure, patience, delay, maturity, and karmic effort.",
      positive: "Its placement shows where steady work, accountability, and long-term planning can produce durable results.",
      caution: "Do not read delay as denial; consistency and maturity are Saturn's main remedies."
    },
    Rahu: {
      meaning: "Rahu indicates ambition, unconventional growth, worldly desire, experimentation, and attraction toward new paths.",
      positive: "Its placement can show where bold learning, technology, foreign influence, or unusual strategy opens doors.",
      caution: "Watch obsession, shortcuts, and restless comparison; clarity keeps Rahu constructive."
    },
    Ketu: {
      meaning: "Ketu indicates detachment, spiritual insight, inner learning, past experience, and subtle dissatisfaction.",
      positive: "Its placement can support intuition, research, liberation from ego, and deeper spiritual understanding.",
      caution: "Avoid withdrawing too quickly; integrate insight with practical participation in life."
    }
  },
  hi: {
    Sun: {
      meaning: "सूर्य आत्मविश्वास, पहचान, जीवन शक्ति, अधिकार और नेतृत्व शैली को दर्शाता है।",
      positive: "इसकी राशि और भाव बताते हैं कि जातक अपनी ऊर्जा और आत्म-अभिव्यक्ति किस जीवन क्षेत्र में अधिक लगाता है।",
      caution: "अहंकार और जल्द मान्यता पाने की इच्छा को संतुलित रखें; कार्य की परिपक्वता सबसे पहले आती है।"
    },
    Moon: {
      meaning: "चंद्र मन, भावनाओं, आदतों, मातृ प्रभाव और प्रतिक्रिया शैली को दर्शाता है।",
      positive: "इसकी स्थिति मानसिक लय, सुरक्षा की जरूरत और भावनात्मक संतुलन समझने में मदद करती है।",
      caution: "क्षणिक भावनाओं से निर्णय न लें; शांत संवाद और स्थिर दिनचर्या सहायक रहेगी।"
    },
    Mars: {
      meaning: "मंगल साहस, निर्णय क्षमता, कार्य ऊर्जा, पहल और संघर्ष संभालने की शैली का संकेत देता है।",
      positive: "इसकी स्थिति केंद्रित प्रयास, प्रतिस्पर्धा और दबाव में काम करने की क्षमता को मजबूत कर सकती है।",
      caution: "क्रोध और जल्दबाजी को अनुशासित कार्रवाई में बदलना जरूरी है।"
    },
    Mercury: {
      meaning: "बुध बुद्धि, संवाद, सीखने की क्षमता, व्यापारिक सोच और तर्कपूर्ण निर्णय से जुड़ा है।",
      positive: "इसकी स्थिति लेखन, बोलचाल, वार्ता, विश्लेषण और व्यावहारिक समझ को दिशा देती है।",
      caution: "अधिक विश्लेषण, बिखरा ध्यान और संवेदनशील बातों में असावधान शब्दों से बचें।"
    },
    Jupiter: {
      meaning: "गुरु ज्ञान, मार्गदर्शन, विस्तार, शिक्षक, धर्म और नैतिक दृष्टि का ग्रह है।",
      positive: "इसकी स्थिति सीख, सलाह, उदारता और दीर्घकालीन विकास के क्षेत्रों को दर्शाती है।",
      caution: "आशावाद को अनुशासन और वास्तविक प्रतिबद्धता के साथ जोड़ना लाभकारी रहेगा।"
    },
    Venus: {
      meaning: "शुक्र संबंध, सौंदर्य, सुख-सुविधा, सामंजस्य, कला और जीवन मूल्यों को दर्शाता है।",
      positive: "इसकी स्थिति प्रेम, कूटनीति, रचनात्मकता और जीवन की गुणवत्ता को विकसित करने की दिशा देती है।",
      caution: "सुविधा को टालमटोल न बनने दें; सच्चा सामंजस्य स्पष्ट संवाद से आता है।"
    },
    Saturn: {
      meaning: "शनि अनुशासन, जिम्मेदारी, धैर्य, संरचना, विलंब और परिपक्वता का संकेत देता है।",
      positive: "इसकी स्थिति बताती है कि समय, मेहनत और योजना से स्थायी परिणाम कहां मिल सकते हैं।",
      caution: "विलंब को असफलता न मानें; निरंतरता और परिपक्वता शनि के मुख्य उपाय हैं।"
    },
    Rahu: {
      meaning: "राहु महत्वाकांक्षा, असामान्य रास्ते, तीव्र इच्छाएं और नए अनुभवों की ओर आकर्षण दिखाता है।",
      positive: "इसकी स्थिति तकनीक, विदेशी प्रभाव, साहसी सीख और अलग रणनीति से नए अवसर दे सकती है।",
      caution: "अत्यधिक आसक्ति, शॉर्टकट और तुलना से सावधान रहें; स्पष्टता राहु को रचनात्मक रखती है।"
    },
    Ketu: {
      meaning: "केतु वैराग्य, आंतरिक सीख, आध्यात्मिक दृष्टि और अनुभव से आई गहरी समझ का संकेत देता है।",
      positive: "इसकी स्थिति अंतर्ज्ञान, शोध, अहंकार से दूरी और आध्यात्मिक परिपक्वता को सहारा देती है।",
      caution: "बहुत जल्दी अलग न हों; समझ को व्यवहारिक जीवन में संतुलित रूप से लागू करें।"
    }
  },
  hinglish: {
    Sun: {
      meaning: "Sun identity, confidence, vitality, authority aur leadership style ko dikhata hai.",
      positive: "Iski rashi aur bhav batate hain ki self-expression aur purpose kis life area me zyada active hota hai.",
      caution: "Pride ko humility ke saath balance karein; recognition se pehle kaam mature hona zaruri hai."
    },
    Moon: {
      meaning: "Moon emotions, mind, habits, motherly influence aur response style ko dikhata hai.",
      positive: "Iski placement emotional needs, public response aur inner security ki rhythm samjhati hai.",
      caution: "Temporary mood se decision na lein; calm communication aur routine helpful rahenge."
    },
    Mars: {
      meaning: "Mars courage, action, initiative, energy aur conflict handling style ka signal deta hai.",
      positive: "Iski placement focused effort, ambition aur pressure me action ko support kar sakti hai.",
      caution: "Anger aur urgency ko impulsive decision ke bajay disciplined action me channel karein."
    },
    Mercury: {
      meaning: "Mercury communication, logic, learning, trade, analysis aur decision style se juda hai.",
      positive: "Iski position writing, speaking, negotiation aur practical intelligence ko support karti hai.",
      caution: "Over-analysis, scattered attention aur careless words se bachna useful rahega."
    },
    Jupiter: {
      meaning: "Jupiter wisdom, teachers, guidance, ethics, growth, faith aur long-term understanding ko dikhata hai.",
      positive: "Iski placement learning, counsel, generosity aur dharmic growth ke areas highlight karti hai.",
      caution: "Optimism ko discipline aur realistic commitments ke saath pair karein."
    },
    Venus: {
      meaning: "Venus relationships, harmony, comfort, beauty, values aur support receive karne ki ability dikhata hai.",
      positive: "Iski placement love, art, diplomacy aur quality of life cultivate karne me madad karti hai.",
      caution: "Comfort ko avoidance na banne dein; harmony ke liye honest communication zaruri hai."
    },
    Saturn: {
      meaning: "Saturn discipline, responsibility, structure, patience, delay aur maturity ka grah hai.",
      positive: "Iski placement long-term planning, accountability aur durable results ka area dikhati hai.",
      caution: "Delay ko denial na samjhein; consistency aur maturity Saturn ke main remedies hain."
    },
    Rahu: {
      meaning: "Rahu ambition, unconventional growth, desire, experimentation aur new paths ki attraction dikhata hai.",
      positive: "Iski placement technology, foreign influence, bold learning ya unusual strategy se doors open kar sakti hai.",
      caution: "Obsession, shortcuts aur comparison se bachkar clarity maintain karein."
    },
    Ketu: {
      meaning: "Ketu detachment, spiritual insight, inner learning aur subtle dissatisfaction ka signal deta hai.",
      positive: "Iski placement intuition, research, ego se distance aur deeper spiritual understanding support karti hai.",
      caution: "Too quickly withdraw na karein; insight ko practical life ke saath integrate karein."
    }
  }
};

function houseInterpretationBlocks(houses: unknown[], lang: Locale) {
  const rows = Array.isArray(houses) ? houses.map(toChartHouse) : [];
  return Array.from({ length: 12 }, (_, index) => {
    const houseNumber = index + 1;
    const house = rows.find((row) => Number(row.house) === houseNumber);
    const planets = planetLabels(house ?? { planets: [] }, lang);
    const area = houseAreaLabels[lang][index];
    const sign = house?.sign ? translateSignValue(house.sign, lang) : safeText(house?.signNumber ?? labels[lang].dash, lang);
    const planetText = planets.length ? planets.join(", ") : labels[lang].dash;
    const theme = houseInterpretationThemes[lang][index];
    if (lang === "hi") {
      const planetNote = planets.length
        ? `यहां ${planetText} का प्रभाव इस जीवन क्षेत्र में ग्रह की भूमिका को सक्रिय करता है।`
        : "इस भाव में कोई प्रमुख ग्रह नहीं है, इसलिए इसके परिणाम भावेश, दृष्टि और संपूर्ण कुंडली संदर्भ से समझे जाने चाहिए।";
      return `${houseNumber}. ${area} | ${labels.hi.sign}: ${sign} | ${labels.hi.planet}: ${planetText}\n${theme} ${planetNote}`;
    }
    if (lang === "hinglish") {
      const planetNote = planets.length
        ? `Yahan ${planetText} ka influence is life area me grah ki role ko activate karta hai.`
        : "Is bhav me koi major planet nahi hai, isliye results ko lord, aspects aur full chart context se samjhein.";
      return `${houseNumber}. ${area} | ${labels.hinglish.sign}: ${sign} | ${labels.hinglish.planet}: ${planetText}\n${theme} ${planetNote}`;
    }
    const planetNote = planets.length
      ? `${planetText} activates this life area through the planet's role and condition.`
      : "No major planet is placed here, so results should be read through the house lord, aspects, and full chart context.";
    return `${houseNumber}. ${area} | ${labels.en.sign}: ${sign} | ${labels.en.planet}: ${planetText}\n${theme} ${planetNote}`;
  });
}

const houseAreaLabels: Record<Locale, string[]> = {
  en: ["Self / personality", "Family / wealth / speech", "Courage / communication", "Home / mother / comfort", "Education / children / creativity", "Health / service / challenges", "Marriage / partnership", "Transformation", "Fortune / dharma", "Career / status", "Gains / network", "Expenses / spirituality"],
  hi: ["स्वयं / व्यक्तित्व", "परिवार / धन / वाणी", "साहस / संचार", "घर / माता / सुख", "शिक्षा / संतान / रचनात्मकता", "स्वास्थ्य / सेवा / चुनौतियां", "विवाह / साझेदारी", "परिवर्तन", "भाग्य / धर्म", "करियर / प्रतिष्ठा", "लाभ / नेटवर्क", "खर्च / आध्यात्मिकता"],
  hinglish: ["Self / personality", "Family / wealth / speech", "Courage / communication", "Home / mother / comfort", "Education / children / creativity", "Health / service / challenges", "Marriage / partnership", "Transformation", "Fortune / dharma", "Career / status", "Gains / network", "Expenses / spirituality"]
};

const houseInterpretationThemes: Record<Locale, string[]> = {
  en: [
    "The first house reflects personality, body, self-image, and the native's first response to life.",
    "The second house relates to family, wealth, speech, values, and the way resources are handled.",
    "The third house shows courage, communication, siblings, initiative, and practical effort.",
    "The fourth house reflects home, mother, emotional comfort, property, and inner stability.",
    "The fifth house relates to education, creativity, children, intelligence, and inspired expression.",
    "The sixth house describes health routines, service, discipline, competition, debts, and challenges.",
    "The seventh house reflects marriage, partnership, public dealings, and the way agreements are built.",
    "The eighth house points to transformation, research, hidden matters, shared resources, and resilience.",
    "The ninth house relates to fortune, dharma, higher learning, teachers, faith, and long journeys.",
    "The tenth house shows career, status, responsibility, public work, and visible contribution.",
    "The eleventh house reflects gains, networks, aspirations, elder support, and long-term fulfillment.",
    "The twelfth house relates to expenses, solitude, sleep, foreign links, release, and spirituality."
  ],
  hi: [
    "पहला भाव व्यक्तित्व, शरीर, आत्म-छवि और जीवन की पहली प्रतिक्रिया को दर्शाता है।",
    "दूसरा भाव परिवार, धन, वाणी और मूल्य प्रणाली से जुड़ा है।",
    "तीसरा भाव साहस, संवाद, भाई-बहन, पहल और व्यावहारिक प्रयास को दर्शाता है।",
    "चौथा भाव घर, माता, भावनात्मक सुख, संपत्ति और आंतरिक स्थिरता से जुड़ा है।",
    "पांचवां भाव शिक्षा, रचनात्मकता, संतान, बुद्धि और प्रेरित अभिव्यक्ति को दर्शाता है।",
    "छठा भाव स्वास्थ्य दिनचर्या, सेवा, अनुशासन, प्रतियोगिता, ऋण और चुनौतियों को दर्शाता है।",
    "सातवां भाव विवाह, साझेदारी, सार्वजनिक व्यवहार और समझौते बनाने की शैली को दर्शाता है।",
    "आठवां भाव परिवर्तन, शोध, गुप्त विषय, साझा संसाधन और धैर्य को दर्शाता है।",
    "नवां भाव भाग्य, धर्म, उच्च शिक्षा, गुरु, विश्वास और लंबी यात्राओं से जुड़ा है।",
    "दसवां भाव करियर, प्रतिष्ठा, जिम्मेदारी, सार्वजनिक कार्य और योगदान को दर्शाता है।",
    "ग्यारहवां भाव लाभ, नेटवर्क, आकांक्षा, बड़े सहयोग और दीर्घकालीन पूर्णता को दर्शाता है।",
    "बारहवां भाव खर्च, एकांत, नींद, विदेश संबंध, त्याग और आध्यात्मिकता से जुड़ा है।"
  ],
  hinglish: [
    "First house personality, body, self-image aur life ke first response ko dikhata hai.",
    "Second house family, wealth, speech, values aur resources handle karne ka tareeka dikhata hai.",
    "Third house courage, communication, siblings, initiative aur practical effort ko show karta hai.",
    "Fourth house home, mother, emotional comfort, property aur inner stability se linked hai.",
    "Fifth house education, creativity, children, intelligence aur inspired expression se juda hai.",
    "Sixth house health routines, service, discipline, competition, debts aur challenges ko dikhata hai.",
    "Seventh house marriage, partnership, public dealing aur agreements build karne ka style dikhata hai.",
    "Eighth house transformation, research, hidden matters, shared resources aur resilience ko point karta hai.",
    "Ninth house fortune, dharma, higher learning, teachers, faith aur long journeys se linked hai.",
    "Tenth house career, status, responsibility, public work aur visible contribution dikhata hai.",
    "Eleventh house gains, networks, aspirations, elder support aur long-term fulfillment ko show karta hai.",
    "Twelfth house expenses, solitude, sleep, foreign links, release aur spirituality se related hai."
  ]
};

function fallbackRemedies(lang: Locale) {
  return {
    en: [
      "Keep a steady daily prayer or meditation routine.",
      "Respect elders and teachers; offer service where possible.",
      "Use chart insights for reflection and planning, not fear-based decisions."
    ],
    hi: [
      "प्रतिदिन शांत प्रार्थना या ध्यान की छोटी दिनचर्या रखें।",
      "बड़ों और गुरुजनों का सम्मान करें और संभव हो तो सेवा करें।",
      "कुंडली संकेतों का उपयोग आत्मचिंतन और योजना के लिए करें, भय के लिए नहीं।"
    ],
    hinglish: [
      "Roz chhoti prayer ya meditation routine rakhein.",
      "Bade aur teachers ka samman karein; possible ho to seva karein.",
      "Chart insights ko reflection aur planning ke liye use karein, fear ke liye nahi."
    ]
  }[lang];
}

type InsightSection = "lagna" | "nakshatra" | "personality" | "career" | "finance" | "relationship" | "health" | "ai";

const insightFallbacks: Record<Locale, Record<InsightSection, string>> = {
  en: {
    lagna: "The available lagna and planetary details support a practical reading of personality, decision style, and life direction.",
    nakshatra: "Nakshatra details are used as a subtle guide for temperament, emotional rhythm, and timing awareness.",
    personality: "The chart points toward a thoughtful personality that benefits from structure, patient decisions, and consistent self-improvement.",
    career: "Career indications should be read through discipline, skills, timing, and the strength of relevant houses.",
    finance: "Financial growth is supported by steady planning, careful risk review, and disciplined saving habits.",
    relationship: "Relationship guidance is best understood through emotional steadiness, communication, and family alignment.",
    health: "Well-being guidance is reflective and non-medical; maintain routine, rest, and professional care when needed.",
    ai: "AI interpretation is currently limited. Use the available chart, Panchang, and planetary sections for grounded reflection."
  },
  hi: {
    lagna: "उपलब्ध लग्न और ग्रह विवरण व्यक्तित्व, निर्णय शैली और जीवन दिशा को व्यावहारिक रूप से समझने में मदद करते हैं।",
    nakshatra: "नक्षत्र विवरण स्वभाव, भावनात्मक लय और समय की समझ के लिए सूक्ष्म मार्गदर्शन देता है।",
    personality: "कुंडली विचारशील व्यक्तित्व, संरचना, धैर्यपूर्ण निर्णय और निरंतर आत्म-सुधार की आवश्यकता को दर्शाती है।",
    career: "करियर संकेतों को अनुशासन, कौशल, समय और संबंधित भावों की शक्ति के साथ समझना उचित है।",
    finance: "वित्तीय विकास स्थिर योजना, जोखिम की सावधानीपूर्वक समीक्षा और अनुशासित बचत आदतों से समर्थित होता है।",
    relationship: "संबंध मार्गदर्शन भावनात्मक स्थिरता, संवाद और परिवारिक सामंजस्य के आधार पर समझें।",
    health: "स्वास्थ्य संकेत चिंतन के लिए हैं, चिकित्सा सलाह नहीं; दिनचर्या, आराम और आवश्यक होने पर विशेषज्ञ सलाह रखें।",
    ai: "AI व्याख्या अभी सीमित है। उपलब्ध चार्ट, पंचांग और ग्रह स्थिति के आधार पर शांत चिंतन करें।"
  },
  hinglish: {
    lagna: "Available lagna aur grah details personality, decision style aur life direction ko practical tareeke se samjhate hain.",
    nakshatra: "Nakshatra details temperament, emotional rhythm aur timing awareness ke liye subtle guidance dete hain.",
    personality: "Chart thoughtful personality, structure, patient decisions aur consistent self-improvement ki need dikhata hai.",
    career: "Career indications ko discipline, skills, timing aur relevant houses ki strength ke saath samjhein.",
    finance: "Financial growth steady planning, careful risk review aur disciplined saving habits se support hoti hai.",
    relationship: "Relationship guidance emotional steadiness, communication aur family alignment se samajhna best hai.",
    health: "Well-being guidance reflective hai, medical advice nahi; routine, rest aur zarurat par expert care rakhein.",
    ai: "AI interpretation abhi limited hai. Available chart, Panchang aur grah sections se grounded reflection karein."
  }
};

function requirePdfReact() {
  const getBuiltinModule = (process as typeof process & {
    getBuiltinModule?: (name: string) => typeof import("node:module");
  }).getBuiltinModule;
  const nodeModule = getBuiltinModule?.("module");
  const externalRequire = nodeModule?.createRequire(`${process.cwd()}/package.json`);
  if (!externalRequire) throw new Error("Node module loader unavailable for PDF renderer");
  return externalRequire("react") as typeof import("react");
}
